[
    {
        "ID": 293420846,
        "key": "Brawlers are unmatched in unarmed combat, and physical exercise tends to leave them in good shape.",
        "original": "Brawlers are unmatched in unarmed combat, and physical exercise tends to leave them in good shape.",
        "translation": "格斗家在徒手格斗中无可匹敌，体育锻炼给了他们良好的状态。",
        "stage": 1,
        "context": "this.m.BackgroundDescription = 'Brawlers are unmatched in unarmed combat, and physical exercise tends to leave them in good shape.'"
    },
    {
        "ID": 293420847,
        "key": "%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disa",
        "original": "%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disappeared, as did his speed and power. He was left jobbing, intentionally taking falls and losing badly when he didn't. Eventually, no one would give him a fight. A nobleman offered him a large sum to wrestle a bear and the desperate %name% took him up on it. When the 'fight' was over, the brawler lay dead, mangled beyond recognition, being dragged around the mud by a ferocious beast as drunken highborn cheered and clapped.",
        "translation": "鉴于留下只有死路一条，%name%退出了行将解体的战团。他回到了拳击赛场，并在接下来的几年里，苦苦挣扎于周赛之中。随着年龄的增长，他失去了他的下巴，也失去了速度和力量。他只能打假赛，故意倒下，或是因为没倒成被暴打。最终，没有人愿意和他比赛了。一个贵族给出了高价佣金，让他和一只熊搏斗，绝望的%name%接受了这个挑战。贵族喝得酩酊大醉，在他们的欢呼叫好声中，这场“战斗”结束了，面目全非的格斗家毫无生气地躺在泥水中，任由凶猛的野兽拖来拖去。",
        "stage": 1,
        "context": "this.m.BadEnding = \"%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disappeared, as did his speed and power. He was left jobbing, intentionally taking falls and losing badly when he didn't. Eventually, no one would give him a fight. A nobleman offered him a large sum to wrestle a bear and the desperate %name% took him up on it. When the 'fight' was over, the brawler lay dead, mangled beyond recognition, being dragged around the mud by a ferocious beast as drunken highborn cheered and clapped.\""
    },
    {
        "ID": 293420848,
        "key": "Brawler",
        "original": "Brawler",
        "translation": "格斗家",
        "stage": 5,
        "context": "this.m.Name = 'Brawler'"
    },
    {
        "ID": 293420849,
        "key": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a caree",
        "original": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}",
        "translation": "{身材魁梧，拳似沙包，过去的一年里，%name%一直在与他的同伴磨练拳技。 | 从那张扭曲成指关节形状的脸就能看出，%name%是个职业斗士。 | %name%喜欢喝酒，就像他喜欢打架一样，真是个强有力的组合。 | 父亲和哥哥们的棍棒教育把%name%磨练成了一个喜怒无常的斗士。 | 年少时期受到的霸凌把%name%锤炼成了一个信奉先下手为强的男子汉。 | %name%只有一项称得上才能的东西：用拳头把别人揍得鼻血直流，自己则无论如何也不倒下。 | 在成长过程中，%name%会和家庭农场里的公牛搏斗。不巧的是，他也会抽时间去城里冒险。}{在过去的一年中，他一直受雇于当地的一位领主，四处巡游，与王室的冠军们搏击。 | 作为酒吧斗殴的爱好者，这名男子显然已经被许多酒馆禁止进入。 | 在%randomtown%中成为出名的斗士意味着他必须与每一个自负、自夸和醉酒的人战斗。 | 尽管他成为了一名不败的职业斗士，但他挣的钱只够勉强维持生计。 | 他脾气火暴，总是乐意开打。当地的格斗组织说他的左钩拳非常狠。}{听说有更大的架能打，%name%放下了拳套，从事更赚钱的佣兵职业。 | 只有一个人能击败%name%：他的妻子。被骂成是胸无大志的丢人现眼之徒，他决定从事更“有尊严”的佣兵工作。 | 多年的战斗基本摧毁了他的记忆。有人说他是把雇佣兵营地看成了购物清单上的项目。 | 赚钱太少，手坏得张都张不开，连抱儿子都抱不了，更别说打拳了，%name%决定找一项新工作。 | 虽然他对真正的战争知之甚少，但在经历了多年的艰苦之后，佣兵的固定报酬实在是诱人。 | 这个人能杀死一块石头，打伤一块巨岩 —— 凡是打架的队伍里都能用上他。}",
        "stage": 1,
        "context": "return \"{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}\";"
    },
    {
        "ID": 293420850,
        "key": "]+100%[/color] Damage when unarmed",
        "original": "]+100%[/color] Damage when unarmed",
        "translation": "]+100%[/color] 徒手伤害",
        "stage": 1,
        "context": "text = '[color=' + this.Const.UI.Color.PositiveValue + ']+100%[/color] Damage when unarmed'"
    },
    {
        "ID": 293420851,
        "key": "A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizef",
        "original": "A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizefighting, shook your hand, and thanked you for giving him the opportunity. Last you heard, the company chose him for a one-on-one, winner take all fight to settle compensation differences with a competing mercenary band. He won in the first round.",
        "translation": "像%name%这样的格斗家，只用拳头就很有威胁，而他也成功证明自己，用起武器也毫不逊色。在你离开%companyname%之前，你就要不要留在战团的问题找他谈过。他说他不想重返拳击比赛，并和你握手，感谢你给了他这个机会。最近你听说，战团和其他同行就赔偿问题起了争执，协议通过单挑比拳胜者决定，战团派他上场。而他在第一轮就奠定了胜局。",
        "stage": 1,
        "context": "this.m.GoodEnding = \"A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizefighting, shook your hand, and thanked you for giving him the opportunity. Last you heard, the company chose him for a one-on-one, winner take all fight to settle compensation differences with a competing mercenary band. He won in the first round.\""
    },
    {
        "key": "%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disappeared, as did his speed and power. He was left jobbing, intentionally taking falls and losing badly when he didn't. Eventually, no one would give him a fight. A nobleman offered him a large sum to wrestle a bear and the desperate %name% took him up on it. When the 'fight' was over, the brawler lay dead, mangled beyond recognition, being dragged around the mud by a ferocious beast as drunken highborn cheered and clapped.",
        "original": "%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disappeared, as did his speed and power. He was left jobbing, intentionally taking falls and losing badly when he didn't. Eventually, no one would give him a fight. A nobleman offered him a large sum to wrestle a bear and the desperate %name% took him up on it. When the 'fight' was over, the brawler lay dead, mangled beyond recognition, being dragged around the mud by a ferocious beast as drunken highborn cheered and clapped.",
        "translation": "",
        "context": "this.m.BadEnding = \"%name% the brawler left the company when it became clear it would soon dissolve and probably end up killing everyone who stayed onboard. He returned to prizefighting, grinding out the following years in brutal, weekly bouts. As he got older, his chin disappeared, as did his speed and power. He was left jobbing, intentionally taking falls and losing badly when he didn't. Eventually, no one would give him a fight. A nobleman offered him a large sum to wrestle a bear and the desperate %name% took him up on it. When the 'fight' was over, the brawler lay dead, mangled beyond recognition, being dragged around the mud by a ferocious beast as drunken highborn cheered and clapped.\""
    },
    {
        "key": "A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizefighting, shook your hand, and thanked you for giving him the opportunity. Last you heard, the company chose him for a one-on-one, winner take all fight to settle compensation differences with a competing mercenary band. He won in the first round.",
        "original": "A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizefighting, shook your hand, and thanked you for giving him the opportunity. Last you heard, the company chose him for a one-on-one, winner take all fight to settle compensation differences with a competing mercenary band. He won in the first round.",
        "translation": "",
        "context": "this.m.GoodEnding = \"A brawler like %name% is dangerous with just his fists, and proved himself similarly savage with weapons. Before you left the %companyname%, you talked to the fighter about whether or not he'd stay in the band. He said he had no desire to return to prizefighting, shook your hand, and thanked you for giving him the opportunity. Last you heard, the company chose him for a one-on-one, winner take all fight to settle compensation differences with a competing mercenary band. He won in the first round.\""
    },
    {
        "key": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}",
        "original": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}",
        "translation": "",
        "context": "onBuildDescription = function onBuildDescription(){\n    return \"{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}\";;\n    return;\n}"
    },
    {
        "key": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}",
        "original": "{Burly and with churchbells for fists, %name% has spent much of the past year sharpening his boxing skills on the grindstone that is his fellow man. | With a face contorted to the shapes of others' knuckles, it's not hard to realize that %name% is a career fighter. | %name% loves the drink as much as he does a good fight, a potent combination. | A hard upbringing by his father and brothers honed %name% into being a temperamental fighter. | Bullies in %name%'s spriteful youth forged him into a man that prefers to seek out a fight rather than wait for it to come to him.  | %name% only ever had one real talent: using his fists to bloody the noses of other men and not going down no matter what. | Growing up, %name% wrestled bulls on the family farm. Unfortunately for men, he found time to venture into the cities.} {For the past year he has been employed by a local lord, paraded around to fistfight the champions of royalty. | A lover of the bar brawl, the man has apparently been banned from too many taverns to count. | Gaining notoriety as a fighter in %randomtown% meant he had to fight every single proud, boasting, and drunk man who came his way. | Although he became an undefeated prizefighter, he was hardly earning enough to get by. | Fiery in spirit, he's always willing to take up fisticuffs. Local fighting rings say he's got a mean left hook.} {Hearing of greater fights to be had, %name% has put down his mitts to take up the more lucrative vocation of being a sellsword. | Only one person has bested %name%: his wife. After she chided him for being an embarrassment with no ambition, he decided to take up the more 'prestigious' field of mercenary work. | Years of martial combat practically destroyed his memory. Some think he mistook a mercenary camp as an item on his shopping list. | Very low on crowns and barely able to open his broken hands to hug his own son much less throw a punch, %name% seeks a new career. | After years of hardship, the promise of regular pay for mercenary work is a tempting offer for him, even though he has little idea of actual warfare. | This man could murder a rock and injure a stone - a good addition to any outfit.}",
        "translation": "",
        "context": ""
    }
]