[
    {
        "ID": 293420876,
        "key": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cl",
        "original": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.",
        "translation": "郁郁寡欢，偶有自我毁灭倾向，%name%时常只凭一把大型双手武器冲入敌阵。{他身上杀气腾腾，曾把人竖着劈成两半。 | 据说他曾经把兽人战士劈成两半，只留下两条腿立在地上。 | 此人以为了给敌人带去死亡，全然不顾自己安危而闻名。 | 他喜欢身处战场中心，不顾安全和准头地挥舞着武器。 | 据说，他赢下过一场骑枪比武，但因睡了围观贵族的老婆被迫逃跑。 | 这人不是个杀手，但完全可以是，甚至是很成功的一个。 | 这人简直势不可挡，幸亏他是你这边的。 | 他曾在嗜杀盛怒中把两只地精穿成了串儿。 | %name%是头强壮的猛兽，反手一击就能杀人。}凡是你给的武器他都会用，但%name%还是偏爱那些摧骨毁肉的大家伙。",
        "stage": 1,
        "context": "return \"Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.\";"
    },
    {
        "ID": 293420877,
        "key": "He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leade",
        "original": "He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leadership, he is making you about as proud as any son could. Ironically, he hates the notion of you being a father figure to him, and you always tell him you'd never father a son so ugly to begin with. You keep in touch to this day.",
        "translation": "战团成立之初，%name%就和你在一起，在你退休后不久，他也追随你的脚步，离开了战团。但他并没有结束战斗，而是开始为另一个战团 —— 他自己的战团而战。在你的领导下，他学到了很多，你为他感到自豪，就像是为自己的儿子。讽刺的是，他讨厌你扮演父亲的角色，而你总是告诉他，你绝没有这么难看的儿子。现在你们还是保持着联系。",
        "stage": 1,
        "context": "this.m.GoodEnding = \"He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leadership, he is making you about as proud as any son could. Ironically, he hates the notion of you being a father figure to him, and you always tell him you'd never father a son so ugly to begin with. You keep in touch to this day.\""
    },
    {
        "ID": 293420878,
        "key": "Companion",
        "original": "Companion",
        "translation": "伙伴",
        "stage": 5,
        "context": "this.m.Name = 'Companion'"
    },
    {
        "ID": 293420879,
        "key": "With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own c",
        "original": "With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own company and was in dire need of help. Unfortunately, the message was dated to nearly a full year ago. When you investigated the existence of his company, you learned that it had been completely annihilated in a battle between nobles.",
        "translation": "战团成立之初，%name%就和你在一起。他既忠诚又有本领。呆了一段时间之后，他最终离开了战团，开创自己的事业。几天前，你收到了这位雇佣兵的来信，信中说，他开始经营自己的战团，并急需帮助。不幸的是，这封信的落款是在一年以前。你调查了他战团的存续情况，得知它已经在贵族的战争中全军覆没了。",
        "stage": 1,
        "context": "this.m.BadEnding = 'With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own company and was in dire need of help. Unfortunately, the message was dated to nearly a full year ago. When you investigated the existence of his company, you learned that it had been completely annihilated in a battle between nobles.'"
    },
    {
        "key": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.",
        "original": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.",
        "translation": "",
        "context": ""
    },
    {
        "key": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.",
        "original": "Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.",
        "translation": "",
        "context": "onBuildDescription = function onBuildDescription(){\n    return \"Brooding and at times suicidal, it's no surprise that %name% is frequently found diving into battle with nothing more than a large two-hander. {Clothed in murderous intent, you once saw him cleave a man in two - top to bottom. | It is said that he once cleaved a warrior orc in two, leaving the trunk of its legs still standing. | The man is known to ignore the fragility of his own mortality just to end the life of another. | He thrives being in the thick of battle where he can swing his weapons with little regard for safety or accuracy. | Supposedly, he once won a jousting tournament, but had to flee after bedding a watching nobleman's wife. | The man is not a murderer, but he would have made a fine one. | Seemingly unstoppable at times, you are glad to have the man on your side. | In a fit of bloodthirsty rage he once impaled two goblins on one pike. | A strong brute, you once saw %name% kill someone just on his backswing.} He'll use any weapon you give him, but %name% has a proclivity towards those that can make calamitous ruin out of a man's body.\";;\n    return;\n}"
    },
    {
        "key": "He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leadership, he is making you about as proud as any son could. Ironically, he hates the notion of you being a father figure to him, and you always tell him you'd never father a son so ugly to begin with. You keep in touch to this day.",
        "original": "He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leadership, he is making you about as proud as any son could. Ironically, he hates the notion of you being a father figure to him, and you always tell him you'd never father a son so ugly to begin with. You keep in touch to this day.",
        "translation": "",
        "context": "this.m.GoodEnding = \"He was with you from the start, %name%, and he was with you in retirement, leaving the company not long after you did. But he wasn't yet done with the fighting life and took up fighting for another company - his own. Having learned so much from your leadership, he is making you about as proud as any son could. Ironically, he hates the notion of you being a father figure to him, and you always tell him you'd never father a son so ugly to begin with. You keep in touch to this day.\""
    },
    {
        "key": "With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own company and was in dire need of help. Unfortunately, the message was dated to nearly a full year ago. When you investigated the existence of his company, you learned that it had been completely annihilated in a battle between nobles.",
        "original": "With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own company and was in dire need of help. Unfortunately, the message was dated to nearly a full year ago. When you investigated the existence of his company, you learned that it had been completely annihilated in a battle between nobles.",
        "translation": "",
        "context": "this.m.BadEnding = \"With you from the start, %name% was as loyal as he was talented. He stayed with the company for a time before eventually leaving to forge out a path for himself. The other day, you received a letter from the mercenary stating that he had started his own company and was in dire need of help. Unfortunately, the message was dated to nearly a full year ago. When you investigated the existence of his company, you learned that it had been completely annihilated in a battle between nobles.\""
    }
]