[
  {
    "ID": 293413117,
    "key": "War is upon us.",
    "original": "War is upon us.",
    "translation": "战争就要来了。",
    "stage": 1,
    "context": "Text = 'War is upon us.'"
  },
  {
    "ID": 293413118,
    "key": "[img]gfx/ui/events/event_92.png[/img]You enter %townname% and find a group of laymen standing around a wooden platform. Thinking there's a hanging to be seen, you quickly push through the crowd. What you find instead is a queerly dressed man barking out n",
    "original": "[img]gfx/ui/events/event_92.png[/img]You enter %townname% and find a group of laymen standing around a wooden platform. Thinking there's a hanging to be seen, you quickly push through the crowd. What you find instead is a queerly dressed man barking out news to the townsfolk.%SPEECH_ON%Harken harken harken, a determination has been made between the noble houses %noblehouse1% and %noblehouse2%! They have come to a conclusion all sides can agree upon: they hate one another!%SPEECH_OFF%Nervous whispers wrinkle the crowd. As the volume builds, the whispers crescendo into hushes. The minstrel continues.%SPEECH_ON%That is right, my fair fair-folk! War is upon us! Ah yes, that fickle beast which lies dormant in all men. A sad affair, a righteous affair, an honorable one!%SPEECH_OFF%An old man standing in front of you grumbles and spits. He leaves, shaking his head and murmuring to himself. The minstrel presses on, his excitement not matching the terrified faces before him.%SPEECH_ON%Let us not dawdle on ceremony. I've been instructed to speak thusly: men, take up arms where you can, plough the fields while you can't. Women, raise yer sons right, lest they may raise a sword all wrong!%SPEECH_OFF%Finally, the minstrel takes a great big breath.%SPEECH_ON%And those among you who wish to earn a good crown or two, the noble houses are looking for the fine services of any man who can swing a sword. Those among you of lesser honor, you bridle-loosers, bride-stealers, leech-sellers, smellsmocks, ne'er do wells, vice obsessed and run amuck, brigands, bandits, and thieving graduates, you sickly and poison moistened, the cursed and rabid, the cured and vapid, sellswords and poets selling words, this, my fine genteel men, is YOUR time. Go out there, fight for the nobles, and earn yourself a new life! A shame that a war shan't last forever, so best do it quick!%SPEECH_OFF%It looks as though the %companyname%'s future just got brighter - on account of the loads of gold you're about to be earning.",
    "translation": "[img]gfx/ui/events/event_92.png[/img]你进入 %townname%，发现一群村民站在一个木制平台周围。 你以为有什么悬着的东西等着看，便迅速地从人群中挤了过去。 结果恰恰相反，你发现一个穿着奇怪的男人在向镇民;大声宣布新闻。%SPEECH_ON%瞧一瞧啊，看一看啊，贵族家族 %noblehouse1% 与 %noblehouse2% 之间互相仇恨！他们要全面开战了！%SPEECH_OFF%人群之中传来窃窃私语的声音。 随着音量越来越大，低语声逐渐消失。吟游诗人继续道。%SPEECH_ON%是的，村民们！ 战争就要来了！ 啊，是的，那个潜伏在所有人心中的变幻无常的野兽。 一件可悲的事，一件正义的事，一件光荣的事！%SPEECH_OFF%站在你面前的一位老人嘟哝着吐口水。 他走了，摇摇头，自言自语。 吟游诗人继续前进，他的兴奋与他面前惊恐的面孔极不相称。%SPEECH_ON%我们不要在仪式上磨磨蹭蹭的。 男人们，拿起你们能拿的武器，在不拿武器的时候多耕地！ 女人们，把你们的儿子养好，免得他们连剑都拿不起来！%SPEECH_OFF%最后，吟游诗人深吸了一口气。%SPEECH_ON%而你们当中那些希望获得一两个克朗的人，贵族家族正在寻找任何能挥剑的人的优质服务。 你们这些不太体面的人，你们这些放荡的，偷新娘的，卖水蛭的，臭气熏天的，不干好事的，恶习成性的，胡作非为的人，还有强盗，土匪，偷东西的，病态的，染毒的，被诅咒的，狂暴的，被治愈的，愚蠢的，佣兵，吟游诗人等等，先生们，现在是你们表现的时间了。 为贵族而战，为自己赢得新生活！ 战争不会永远持续下去，出人头地要乘早！%SPEECH_OFF%看起来好像 %companyname%的未来要变得更加光明了，因为你将会赚到大量的金子。",
    "stage": 1,
    "context": "Text = \"[img]gfx/ui/events/event_92.png[/img]You enter %townname% and find a group of laymen standing around a wooden platform. Thinking there's a hanging to be seen, you quickly push through the crowd. What you find instead is a queerly dressed man barking out news to the townsfolk.%SPEECH_ON%Harken harken harken, a determination has been made between the noble houses %noblehouse1% and %noblehouse2%! They have come to a conclusion all sides can agree upon: they hate one another!%SPEECH_OFF%Nervous whispers wrinkle the crowd. As the volume builds, the whispers crescendo into hushes. The minstrel continues.%SPEECH_ON%That is right, my fair fair-folk! War is upon us! Ah yes, that fickle beast which lies dormant in all men. A sad affair, a righteous affair, an honorable one!%SPEECH_OFF%An old man standing in front of you grumbles and spits. He leaves, shaking his head and murmuring to himself. The minstrel presses on, his excitement not matching the terrified faces before him.%SPEECH_ON%Let us not dawdle on ceremony. I've been instructed to speak thusly: men, take up arms where you can, plough the fields while you can't. Women, raise yer sons right, lest they may raise a sword all wrong!%SPEECH_OFF%Finally, the minstrel takes a great big breath.%SPEECH_ON%And those among you who wish to earn a good crown or two, the noble houses are looking for the fine services of any man who can swing a sword. Those among you of lesser honor, you bridle-loosers, bride-stealers, leech-sellers, smellsmocks, ne'er do wells, vice obsessed and run amuck, brigands, bandits, and thieving graduates, you sickly and poison moistened, the cursed and rabid, the cured and vapid, sellswords and poets selling words, this, my fine genteel men, is YOUR time. Go out there, fight for the nobles, and earn yourself a new life! A shame that a war shan't last forever, so best do it quick!%SPEECH_OFF%It looks as though the %companyname%'s future just got brighter - on account of the loads of gold you're about to be earning.\""
  },
  {
    "ID": 293413119,
    "key": "At %townname%",
    "original": "At %townname%",
    "translation": "在%townname%",
    "stage": 1,
    "context": "this.m.Title = 'At %townname%'"
  }
]
