[
    {
        "ID": 293413095,
        "key": " suffers ",
        "original": " suffers ",
        "translation": " 遭受 ",
        "stage": 5,
        "context": "text = bro.getName() + ' suffers ' + injury.getNameOnly()"
    },
    {
        "ID": 293413096,
        "key": "The company gained renown",
        "original": "The company gained renown",
        "translation": "战团获得了名望",
        "stage": 5,
        "context": "text = 'The company gained renown'"
    },
    {
        "ID": 293413097,
        "key": "This is our food and we decide what we do with it!",
        "original": "This is our food and we decide what we do with it!",
        "translation": "这是我们的食物，只有我们才能决定怎么处理它！",
        "stage": 1,
        "context": "Text = 'This is our food and we decide what we do with it!'"
    },
    {
        "ID": 293413098,
        "key": "You killed some of their men",
        "original": "You killed some of their men",
        "translation": "你杀了他们的一些人",
        "stage": 1,
        "context": "_event.m.NobleHouse.addPlayerRelation(this.Const.World.Assets.RelationOffense, 'You killed some of their men')"
    },
    {
        "ID": 293413099,
        "key": "You lose ",
        "original": "You lose ",
        "translation": "你失去了",
        "stage": 5,
        "context": "text = 'You lose ' + item.getName()"
    },
    {
        "ID": 293413100,
        "key": "[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick bla",
        "original": "[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick blade about his neck, you call out to the rest of his men.%SPEECH_ON%Is it violence you really want?%SPEECH_OFF%Holding his hands up, the lieutenant squeaks out some words.%SPEECH_ON%Wait, wait, hold on. I think we, uh, made a mistake. This is the wrong village, fellas.%SPEECH_OFF%You nick him with the sword before releasing him. The peasants rejoice as the food goes back to them. No doubt, the nobility will hear of your 'good' deeds done here, but so will the common man.",
        "translation": "[img]gfx/ui/events/event_79.png[/img]军官转向他的士兵，指挥他们抢夺。 你拔出剑，一瘸一拐地走过去，身体一侧的疼痛仍然挥之不去，但是悄悄接近一个男人并不费劲。 你用匕首抵着他脖子，你向他手下的其他人喊道。%SPEECH_ON%你真的想要暴力吗？%SPEECH_OFF%军官举起手，尖声说出了一些话。%SPEECH_ON%等等，等等，都停下。 我想我们，呃，犯了个错误。 伙计们，我们走错村庄了。%SPEECH_OFF%在释放他之前，你先用匕首刺伤了他。 当食物回到农民手中时，他们高兴极了。 毫无疑问，贵族们会听说你在这里所做的“好事”，但是普通人也会听说。",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick blade about his neck, you call out to the rest of his men.%SPEECH_ON%Is it violence you really want?%SPEECH_OFF%Holding his hands up, the lieutenant squeaks out some words.%SPEECH_ON%Wait, wait, hold on. I think we, uh, made a mistake. This is the wrong village, fellas.%SPEECH_OFF%You nick him with the sword before releasing him. The peasants rejoice as the food goes back to them. No doubt, the nobility will hear of your 'good' deeds done here, but so will the common man.\""
    },
    {
        "ID": 293413101,
        "key": "That went south real fast.",
        "original": "That went south real fast.",
        "translation": "事情居然就这样搞砸了。",
        "stage": 1,
        "context": "Text = 'That went south real fast.'"
    },
    {
        "ID": 293413102,
        "key": "The company loses renown",
        "original": "The company loses renown",
        "translation": "战团失去了名望",
        "stage": 5,
        "context": "text = 'The company loses renown'"
    },
    {
        "ID": 293413103,
        "key": "[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner.",
        "original": "[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner. | Giving food is one thing, quarreling with soldiers is another. You inform the soldiers that there will be no fight and that they can carry on. The laymen cry out, begging you to put a stop to it. Some are too weak to say anything, this sudden turn of events having been a bigger blow than any long weeks of hunger.",
        "translation": "[img]gfx/ui/events/event_79.png[/img]你通知你的人撤退。 老百姓哀号着，因为他们的食物又被夺走了。 这是一个可怕的哭声，许多人诅咒你，说他们宁愿你从来没有出现过，也不愿意被这样折磨。 | 给予食物是一回事，与士兵战斗是另一回事。 你告诉士兵们不会有战斗，他们可以继续前进。 村民们叫喊着，乞求你阻止这一切。 有些人虚弱得什么也说不出来，这种突如其来的事态变化比长达数周的饥饿对他们的打击更大。",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner. | Giving food is one thing, quarreling with soldiers is another. You inform the soldiers that there will be no fight and that they can carry on. The laymen cry out, begging you to put a stop to it. Some are too weak to say anything, this sudden turn of events having been a bigger blow than any long weeks of hunger.\""
    },
    {
        "ID": 293413104,
        "key": "You threatened some of their men",
        "original": "You threatened some of their men",
        "translation": "你威胁他们的一些人",
        "stage": 1,
        "context": "_event.m.NobleHouse.addPlayerRelation(this.Const.World.Assets.RelationNobleContractFail, 'You threatened some of their men')"
    },
    {
        "ID": 293413105,
        "key": "[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands cla",
        "original": "[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands clasped together.%SPEECH_ON%Please, would you help us? We have been without food for almost a week now. We're down to eating dirt! You have to understand, we have nothing! The war has ravaged us all.%SPEECH_OFF% | A small hamlet emerges beside your travels, little more than a cursory wink were it not for the large band of villagers standing outside seemingly awaiting you. Their leader steps forward.%SPEECH_ON%Mercenary, I know you are probably not the one to ask for this, but do you have any food to spare? The war has ravaged our crops and the soldiers that roam the land have taken what else there is to take! Please, help us!%SPEECH_OFF% | The roads lead you to a small hamlet. Villagers are squatting outside their hamlets, heads between their knees, looking thin and grey. Children are with them, frail and wiry, yet with the glow of youth still in their eyes. The town's leader comes to you personally.%SPEECH_ON%Sir... sellsword? Yes, sellsword. Please, we've been without food for a week now. We've been surviving on our pets, insects... even the dirt. Do you have anything to help us?%SPEECH_OFF% | As your men take a rest beside the road, villagers from a nearby hamlet come to you. They bumble forward, wiry legs shambling them from side to side. The head of the group raises and lowers a hand as though to bless your presence.%SPEECH_ON%Oh sellsword, mercenary, please, do you have anything to eat? We've yet to have a bite in two days! And what we have eaten are things not to be said aloud! The war between nobles has ruined this place, but maybe you can help?%SPEECH_OFF%}",
        "translation": "[img]gfx/ui/events/event_79.png[/img]{当你在路上走的时候，你遇到了一个小村庄，很明显，几乎所有人都站村外。 他们的村长向前走了几步，伸出双手，恳求着，尽管他虚弱的几乎没有力气把双手合在一起。%SPEECH_ON%拜托，你能帮帮我们吗？ 我们已经将近一个星期没有食物吃了。 我们只能吃土了！ 我们已经什么都没有！ 战争蹂躏了我们所有人。%SPEECH_OFF% | 在你的旅途的路旁出现了一个小村庄，如果不是因为似乎外面站着一大群村民在等你的村民，这只不过是旅途路上的匆匆一瞥。他们的村长走上前来。%SPEECH_ON%雇佣兵，我知道你不是那个能保护我们的人，但是你有多余的食物吗？ 战争蹂躏了我们的庄稼，在这片土地上游荡的士兵们拿走了我们的一切！ 求求你，救救我们！%SPEECH_OFF% | 这条路通向一个小村庄。 村民们蹲在他们的村子外面，头埋在膝盖之间，看上去又瘦又灰。 孩子们和他们在一起，身体虚弱，精力充沛，但他们眼中仍闪烁着青春的光芒。 村长亲自来找你。%SPEECH_ON%先生…是佣兵？是的，佣兵。 求求你，我们已经一个星期没吃东西了。 我们靠我们的宠物，昆虫生存…甚至是泥土。 你能帮帮我们吗？%SPEECH_OFF% | 当你的人在路边休息的时候，附近一个村庄的村民来找你们。 他们蹒跚向前，瘦削的腿从一边到另一边摇晃着。 一群人的头抬起或者低下一只手，好像在祝福你的存在。%SPEECH_ON%噢，佣兵，请问，你有什么吃的吗？ 我们已经两天没有吃东西了！ 我们这几天所吃的，一些根本不能说的东西！ 贵族之间的战争毁了这个地方，你能帮帮我们吗？%SPEECH_OFF%}",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands clasped together.%SPEECH_ON%Please, would you help us? We have been without food for almost a week now. We're down to eating dirt! You have to understand, we have nothing! The war has ravaged us all.%SPEECH_OFF% | A small hamlet emerges beside your travels, little more than a cursory wink were it not for the large band of villagers standing outside seemingly awaiting you. Their leader steps forward.%SPEECH_ON%Mercenary, I know you are probably not the one to ask for this, but do you have any food to spare? The war has ravaged our crops and the soldiers that roam the land have taken what else there is to take! Please, help us!%SPEECH_OFF% | The roads lead you to a small hamlet. Villagers are squatting outside their hamlets, heads between their knees, looking thin and grey. Children are with them, frail and wiry, yet with the glow of youth still in their eyes. The town's leader comes to you personally.%SPEECH_ON%Sir... sellsword? Yes, sellsword. Please, we've been without food for a week now. We've been surviving on our pets, insects... even the dirt. Do you have anything to help us?%SPEECH_OFF% | As your men take a rest beside the road, villagers from a nearby hamlet come to you. They bumble forward, wiry legs shambling them from side to side. The head of the group raises and lowers a hand as though to bless your presence.%SPEECH_ON%Oh sellsword, mercenary, please, do you have anything to eat? We've yet to have a bite in two days! And what we have eaten are things not to be said aloud! The war between nobles has ruined this place, but maybe you can help?%SPEECH_OFF%}\""
    },
    {
        "ID": 293413106,
        "key": "[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss.",
        "original": "[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss. But as he goes about the business, a few soldiers waving the %noblehouse% banner show up. They sift through the hungry crowd, taking food and drawing swords whenever someone resists. Their supposed leader speaks out.%SPEECH_ON%This food is needed by the arm of %noblehouse%. Do not resist its seizure.%SPEECH_OFF%You explain to the man that it is in fact your food and you just handed it out.%SPEECH_ON%If it's your food, why is it in their hands? Go along, men, take all that you can! And don't try anything, sellsword, or there will be violence.%SPEECH_OFF%%randombrother% glances at you as if to say, what should we do?",
        "translation": "[img]gfx/ui/events/event_79.png[/img]好吧。生活是残酷的，为什么不做点让世界更美好的事情呢？ 你命令 %randombrother% 去分发食物，不要发太多，但每个人都要有。 但就在他刚刚分完食物之后，些许 %noblehouse% 的手下出现了。 他们从饥饿的人群中筛选，拿走食物，每当有人反抗时就拔剑。 他们所谓的头子狂妄的说。%SPEECH_ON%这些食物是 %noblehouse% 所需要的。不准拒绝我们。%SPEECH_OFF%你向那个人解释说，这实际上是你的食物，而你只是把它们分发出去。%SPEECH_ON%如果是你的食物，为什么在他们手里？ 去吧，伙计们，尽你们所能！ 别轻举妄动，佣兵，否则我们就不客气了。%SPEECH_OFF%%randombrother% 瞥了你一眼，就好像在说，我们该怎么办？",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss. But as he goes about the business, a few soldiers waving the %noblehouse% banner show up. They sift through the hungry crowd, taking food and drawing swords whenever someone resists. Their supposed leader speaks out.%SPEECH_ON%This food is needed by the arm of %noblehouse%. Do not resist its seizure.%SPEECH_OFF%You explain to the man that it is in fact your food and you just handed it out.%SPEECH_ON%If it's your food, why is it in their hands? Go along, men, take all that you can! And don't try anything, sellsword, or there will be violence.%SPEECH_OFF%%randombrother% glances at you as if to say, what should we do?\""
    },
    {
        "ID": 293413107,
        "key": "[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are",
        "original": "[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are quickly fed by the air of empty bellies. The mercenary tries to maintain order, but anything he says only spurs the hungry masses into thinking it's all his fault. The violence spills over, ironically spilling all the food into the mud. Your brothers have to draw swords and by the end of it some peasants lay dead while the survivors look at the corpses with cannibalistic eyes.\n\nYou quickly order the %companyname% to move on before this gets any worse. | For some reason, perhaps to sleep better at night, you order %randombrother% to hand out parcels of food. He's just getting started on the process when a villager quickly snatches a sack of foods. Another peasant stoves that man's head in and takes the sack for himself. This quickly erupts into a total free-for-all and your mercenaries have to draw weapons to protect the rest of the stores. By the end of the scuffle a few laymen lay dead and your brothers are a little marked up. Seeing no reason to hang around, you order the company to get back on the road. The leader who asked for your help is spotted in the distance, staring out at the horizon as a bitter wind curls his thin pantaloons about his shins.}",
        "translation": "[img]gfx/ui/events/event_79.png[/img]{善良占了上风: 你命令 %randombrother% 开始分发食物。 他答应了，但是当他开始分发的时候，人群几乎疯狂地互相抢夺。 暴躁的脾气很快被空腹的空气所助长。 雇佣兵试图维持秩序，但他所说的一切只会促使饥饿的群众认为这都是他的错。 暴力蔓延开来，具有讽刺意味的是，所有的食物都洒进了泥里。 你的兄弟们必须拔出剑，最后一些农民死了，而幸存者用食人的眼睛看着尸体。\n\n在情况变得更糟之前，你迅速命令 %companyname% 继续前进。 | 出于某种原因，也许为了晚上睡得更好，你命令 %randombrother% 去分发食物。 但他才刚刚开始分发，一个村民就迅速抓起一袋食物。 在旁边的另一个农民把那个村民的头放进炉子里，自己拿袋子。 这很快就演变成一场混战，你的雇佣兵们必须拿出武器来保护其他的粮食。 混战结束时，几个村民死了，你的手下们也受了点伤。 看到没有理由留下来，你命令大伙重新上路。 在远处，你发现了乞求你们帮助的村长，他凝视着远方的地平线，一股刺骨的寒风把他的破裤子卷在小腿上。}",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are quickly fed by the air of empty bellies. The mercenary tries to maintain order, but anything he says only spurs the hungry masses into thinking it's all his fault. The violence spills over, ironically spilling all the food into the mud. Your brothers have to draw swords and by the end of it some peasants lay dead while the survivors look at the corpses with cannibalistic eyes.\n\nYou quickly order the %companyname% to move on before this gets any worse. | For some reason, perhaps to sleep better at night, you order %randombrother% to hand out parcels of food. He's just getting started on the process when a villager quickly snatches a sack of foods. Another peasant stoves that man's head in and takes the sack for himself. This quickly erupts into a total free-for-all and your mercenaries have to draw weapons to protect the rest of the stores. By the end of the scuffle a few laymen lay dead and your brothers are a little marked up. Seeing no reason to hang around, you order the company to get back on the road. The leader who asked for your help is spotted in the distance, staring out at the horizon as a bitter wind curls his thin pantaloons about his shins.}\""
    },
    {
        "ID": 293413108,
        "key": "[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and ",
        "original": "[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and plunge it into his neck. His soldiers come scrambling through the crowd, but your mercenaries cut them down and the peasants finish them off with sheer brutality only hunger can create. The lieutenant slowly slides down from your grip. You stare down at his blackening eyes.%SPEECH_ON%Yes, there will be violence.%SPEECH_OFF%The peasants cheer the results, though you recommend they bury the bodies or, even better, not be here anymore. No doubt an army will wonder where these men went.",
        "translation": "[img]gfx/ui/events/event_79.png[/img]你抓住军官的肩膀把他拉近。 他抓住你的胳膊，把你扔了出去，然后用同样的动作拔出他的剑。 你跳到他身边，挡住了他拔剑，然后迅速拔出匕首，刺入他的脖子。 他的士兵从人群中匆匆而来，但是你的雇佣兵把他们砍倒了，农民们用只有饥饿才能创造出来的残忍把他们杀死。 军官慢慢地从你的手里滑了下来。 你低头看着他那双发黑的眼睛。%SPEECH_ON%对，我们确实不客气了。%SPEECH_OFF%农民们对结果欢呼雀跃，尽管你建议他们埋葬尸体，或者，更好的是，不再留在这里。 毫无疑问，一支军队会想知道这些来征粮的人去了哪里。",
        "stage": 1,
        "context": "Text = '[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and plunge it into his neck. His soldiers come scrambling through the crowd, but your mercenaries cut them down and the peasants finish them off with sheer brutality only hunger can create. The lieutenant slowly slides down from your grip. You stare down at his blackening eyes.%SPEECH_ON%Yes, there will be violence.%SPEECH_OFF%The peasants cheer the results, though you recommend they bury the bodies or, even better, not be here anymore. No doubt an army will wonder where these men went.'"
    },
    {
        "ID": 293413109,
        "key": "Shall they fare better in the coming days.",
        "original": "Shall they fare better in the coming days.",
        "translation": "他们在未来几天会好点吗。",
        "stage": 1,
        "context": "Text = 'Shall they fare better in the coming days.'"
    },
    {
        "ID": 293413110,
        "key": "We should also get going.",
        "original": "We should also get going.",
        "translation": "我们也该走了。",
        "stage": 1,
        "context": "Text = 'We should also get going.'"
    },
    {
        "ID": 293413111,
        "key": "That's our food, but this ain't our fight.",
        "original": "That's our food, but this ain't our fight.",
        "translation": "那是我们的食物，但这不是我们的战斗。",
        "stage": 1,
        "context": "Text = \"That's our food, but this ain't our fight.\""
    },
    {
        "ID": 293413112,
        "key": "Find your own way, peasants.",
        "original": "Find your own way, peasants.",
        "translation": "自力更生吧，农民们。",
        "stage": 1,
        "context": "Text = 'Find your own way, peasants.'"
    },
    {
        "ID": 293413113,
        "key": "Alright, let's give those poor folks some food.",
        "original": "Alright, let's give those poor folks some food.",
        "translation": "好吧，给那些可怜的人们一些食物。",
        "stage": 1,
        "context": "Text = \"Alright, let's give those poor folks some food.\""
    },
    {
        "ID": 293413114,
        "key": "[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sells",
        "original": "[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sellsword as though he was about whisper an immense and unforgettable truth. The leader of the small town says he will spread word of your goodwill. You're actually not sure if news of altruism is good for a mercenary band... | Shocking the villagers, you order %randombrother% to hand out some food. Not too much, just enough that these people can eat. And obviously, don't give away anything too good!\n\n The leader of the town comes to you, shaking hands clapping your shoulders.%SPEECH_ON%You've no idea what this means to us! All shall hear of the good in the...%SPEECH_OFF%He glances at you and then your banner. You nod.%SPEECH_ON%The %companyname%.%SPEECH_OFF%The man laughs.%SPEECH_ON%Of course! Everyone shall hear of the %companyname%!%SPEECH_OFF%}",
        "translation": "[img]gfx/ui/events/event_79.png[/img]{你不是唯利是图的雇佣兵，你选择给穷人一些食物。%randombrother% 被告知要尽可能的分给每个穷人，虽然这样每个人就分不到太多。 村民们感激不尽，他们涌向佣兵，仿佛他要低声说出一个惊天大秘密似的。 这儿的村长说他会传播你的善意。 你实际上并不确定利他主义的新闻是否对雇佣兵团有好处… | 你命令 %randombrother% 给村民分发食物，这个命令震惊了村民。 你没给太多，给的刚好够这些人吃。 显然，不要放弃任何太好的东西！\n\n 这儿的村长向你走来，握着你的手拍着你的肩膀。%SPEECH_ON%你根本不知道这对我们意味着什么！ 所有人都会知道的…%SPEECH_OFF%他瞥着你，然后看着你的旗帜。你点头。%SPEECH_ON%%companyname%。%SPEECH_OFF%这个人笑了笑。%SPEECH_ON%每个人都该知道 %companyname% ！%SPEECH_OFF%}",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sellsword as though he was about whisper an immense and unforgettable truth. The leader of the small town says he will spread word of your goodwill. You're actually not sure if news of altruism is good for a mercenary band... | Shocking the villagers, you order %randombrother% to hand out some food. Not too much, just enough that these people can eat. And obviously, don't give away anything too good!\n\n The leader of the town comes to you, shaking hands clapping your shoulders.%SPEECH_ON%You've no idea what this means to us! All shall hear of the good in the...%SPEECH_OFF%He glances at you and then your banner. You nod.%SPEECH_ON%The %companyname%.%SPEECH_OFF%The man laughs.%SPEECH_ON%Of course! Everyone shall hear of the %companyname%!%SPEECH_OFF%}\""
    },
    {
        "ID": 293413115,
        "key": "Along the road...",
        "original": "Along the road...",
        "translation": "在路上……",
        "stage": 5,
        "context": "this.m.Title = 'Along the road...'"
    },
    {
        "ID": 293413116,
        "key": "Sometimes being stupid feels good.",
        "original": "Sometimes being stupid feels good.",
        "translation": "有时候犯傻感觉很好。",
        "stage": 1,
        "context": "Text = 'Sometimes being stupid feels good.'"
    },
    {
        "ID": 315253933,
        "key": "sha256:51335374627e92a3c63bfd618de206d729ba2adbb17242d405fb77b1227d2a99",
        "original": "Sorry...",
        "translation": "抱歉……",
        "stage": 5,
        "context": "Text = 'Sorry...'"
    },
    {
        "key": "Sorry...",
        "original": "Sorry...",
        "translation": "",
        "context": "Text = \"Sorry...\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick blade about his neck, you call out to the rest of his men.%SPEECH_ON%Is it violence you really want?%SPEECH_OFF%Holding his hands up, the lieutenant squeaks out some words.%SPEECH_ON%Wait, wait, hold on. I think we, uh, made a mistake. This is the wrong village, fellas.%SPEECH_OFF%You nick him with the sword before releasing him. The peasants rejoice as the food goes back to them. No doubt, the nobility will hear of your 'good' deeds done here, but so will the common man.",
        "original": "[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick blade about his neck, you call out to the rest of his men.%SPEECH_ON%Is it violence you really want?%SPEECH_OFF%Holding his hands up, the lieutenant squeaks out some words.%SPEECH_ON%Wait, wait, hold on. I think we, uh, made a mistake. This is the wrong village, fellas.%SPEECH_OFF%You nick him with the sword before releasing him. The peasants rejoice as the food goes back to them. No doubt, the nobility will hear of your 'good' deeds done here, but so will the common man.",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]The lieutenant turns back to his men, directing them in their thievery. You draw your sword and hobble over, the pain in your side still lingering, but it doesn't take much effort to sneak up on a man. With a quick blade about his neck, you call out to the rest of his men.%SPEECH_ON%Is it violence you really want?%SPEECH_OFF%Holding his hands up, the lieutenant squeaks out some words.%SPEECH_ON%Wait, wait, hold on. I think we, uh, made a mistake. This is the wrong village, fellas.%SPEECH_OFF%You nick him with the sword before releasing him. The peasants rejoice as the food goes back to them. No doubt, the nobility will hear of your 'good' deeds done here, but so will the common man.\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss. But as he goes about the business, a few soldiers waving the %noblehouse% banner show up. They sift through the hungry crowd, taking food and drawing swords whenever someone resists. Their supposed leader speaks out.%SPEECH_ON%This food is needed by the arm of %noblehouse%. Do not resist its seizure.%SPEECH_OFF%You explain to the man that it is in fact your food and you just handed it out.%SPEECH_ON%If it's your food, why is it in their hands? Go along, men, take all that you can! And don't try anything, sellsword, or there will be violence.%SPEECH_OFF%%randombrother% glances at you as if to say, what should we do?",
        "original": "[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss. But as he goes about the business, a few soldiers waving the %noblehouse% banner show up. They sift through the hungry crowd, taking food and drawing swords whenever someone resists. Their supposed leader speaks out.%SPEECH_ON%This food is needed by the arm of %noblehouse%. Do not resist its seizure.%SPEECH_OFF%You explain to the man that it is in fact your food and you just handed it out.%SPEECH_ON%If it's your food, why is it in their hands? Go along, men, take all that you can! And don't try anything, sellsword, or there will be violence.%SPEECH_OFF%%randombrother% glances at you as if to say, what should we do?",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]Well. This world is a terrible place and if you can do a little to relieve it of its horrid nature, why not? You order %randombrother% to start doling out food, but not too much, and nothing that your tastes will miss. But as he goes about the business, a few soldiers waving the %noblehouse% banner show up. They sift through the hungry crowd, taking food and drawing swords whenever someone resists. Their supposed leader speaks out.%SPEECH_ON%This food is needed by the arm of %noblehouse%. Do not resist its seizure.%SPEECH_OFF%You explain to the man that it is in fact your food and you just handed it out.%SPEECH_ON%If it's your food, why is it in their hands? Go along, men, take all that you can! And don't try anything, sellsword, or there will be violence.%SPEECH_OFF%%randombrother% glances at you as if to say, what should we do?\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and plunge it into his neck. His soldiers come scrambling through the crowd, but your mercenaries cut them down and the peasants finish them off with sheer brutality only hunger can create. The lieutenant slowly slides down from your grip. You stare down at his blackening eyes.%SPEECH_ON%Yes, there will be violence.%SPEECH_OFF%The peasants cheer the results, though you recommend they bury the bodies or, even better, not be here anymore. No doubt an army will wonder where these men went.",
        "original": "[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and plunge it into his neck. His soldiers come scrambling through the crowd, but your mercenaries cut them down and the peasants finish them off with sheer brutality only hunger can create. The lieutenant slowly slides down from your grip. You stare down at his blackening eyes.%SPEECH_ON%Yes, there will be violence.%SPEECH_OFF%The peasants cheer the results, though you recommend they bury the bodies or, even better, not be here anymore. No doubt an army will wonder where these men went.",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]You grab the lieutenant by the shoulder and pull him close. He grabs you arm and throws you off, going to draw his sword in the same motion. You jump to his side, blocking the draw, and in turn pull a quick dagger and plunge it into his neck. His soldiers come scrambling through the crowd, but your mercenaries cut them down and the peasants finish them off with sheer brutality only hunger can create. The lieutenant slowly slides down from your grip. You stare down at his blackening eyes.%SPEECH_ON%Yes, there will be violence.%SPEECH_OFF%The peasants cheer the results, though you recommend they bury the bodies or, even better, not be here anymore. No doubt an army will wonder where these men went.\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner. | Giving food is one thing, quarreling with soldiers is another. You inform the soldiers that there will be no fight and that they can carry on. The laymen cry out, begging you to put a stop to it. Some are too weak to say anything, this sudden turn of events having been a bigger blow than any long weeks of hunger.",
        "original": "[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner. | Giving food is one thing, quarreling with soldiers is another. You inform the soldiers that there will be no fight and that they can carry on. The laymen cry out, begging you to put a stop to it. Some are too weak to say anything, this sudden turn of events having been a bigger blow than any long weeks of hunger.",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]You inform your men to stand down. The commonfolk wail as their food is taken from them again. It is a horrid cry and many damn you, stating they'd rather you have never shown up at all than be tortured in this manner. | Giving food is one thing, quarreling with soldiers is another. You inform the soldiers that there will be no fight and that they can carry on. The laymen cry out, begging you to put a stop to it. Some are too weak to say anything, this sudden turn of events having been a bigger blow than any long weeks of hunger.\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sellsword as though he was about whisper an immense and unforgettable truth. The leader of the small town says he will spread word of your goodwill. You're actually not sure if news of altruism is good for a mercenary band... | Shocking the villagers, you order %randombrother% to hand out some food. Not too much, just enough that these people can eat. And obviously, don't give away anything too good!\n\n The leader of the town comes to you, shaking hands clapping your shoulders.%SPEECH_ON%You've no idea what this means to us! All shall hear of the good in the...%SPEECH_OFF%He glances at you and then your banner. You nod.%SPEECH_ON%The %companyname%.%SPEECH_OFF%The man laughs.%SPEECH_ON%Of course! Everyone shall hear of the %companyname%!%SPEECH_OFF%}",
        "original": "[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sellsword as though he was about whisper an immense and unforgettable truth. The leader of the small town says he will spread word of your goodwill. You're actually not sure if news of altruism is good for a mercenary band... | Shocking the villagers, you order %randombrother% to hand out some food. Not too much, just enough that these people can eat. And obviously, don't give away anything too good!\n\n The leader of the town comes to you, shaking hands clapping your shoulders.%SPEECH_ON%You've no idea what this means to us! All shall hear of the good in the...%SPEECH_OFF%He glances at you and then your banner. You nod.%SPEECH_ON%The %companyname%.%SPEECH_OFF%The man laughs.%SPEECH_ON%Of course! Everyone shall hear of the %companyname%!%SPEECH_OFF%}",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{Against typical mercenary judgment, you elect to give the poor villagers some food. %randombrother% is told to disperse what he can, although obviously not too much. The people are forever grateful, swarming the sellsword as though he was about whisper an immense and unforgettable truth. The leader of the small town says he will spread word of your goodwill. You're actually not sure if news of altruism is good for a mercenary band... | Shocking the villagers, you order %randombrother% to hand out some food. Not too much, just enough that these people can eat. And obviously, don't give away anything too good!\\n\\n The leader of the town comes to you, shaking hands clapping your shoulders.%SPEECH_ON%You've no idea what this means to us! All shall hear of the good in the...%SPEECH_OFF%He glances at you and then your banner. You nod.%SPEECH_ON%The %companyname%.%SPEECH_OFF%The man laughs.%SPEECH_ON%Of course! Everyone shall hear of the %companyname%!%SPEECH_OFF%}\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are quickly fed by the air of empty bellies. The mercenary tries to maintain order, but anything he says only spurs the hungry masses into thinking it's all his fault. The violence spills over, ironically spilling all the food into the mud. Your brothers have to draw swords and by the end of it some peasants lay dead while the survivors look at the corpses with cannibalistic eyes.\n\nYou quickly order the %companyname% to move on before this gets any worse. | For some reason, perhaps to sleep better at night, you order %randombrother% to hand out parcels of food. He's just getting started on the process when a villager quickly snatches a sack of foods. Another peasant stoves that man's head in and takes the sack for himself. This quickly erupts into a total free-for-all and your mercenaries have to draw weapons to protect the rest of the stores. By the end of the scuffle a few laymen lay dead and your brothers are a little marked up. Seeing no reason to hang around, you order the company to get back on the road. The leader who asked for your help is spotted in the distance, staring out at the horizon as a bitter wind curls his thin pantaloons about his shins.}",
        "original": "[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are quickly fed by the air of empty bellies. The mercenary tries to maintain order, but anything he says only spurs the hungry masses into thinking it's all his fault. The violence spills over, ironically spilling all the food into the mud. Your brothers have to draw swords and by the end of it some peasants lay dead while the survivors look at the corpses with cannibalistic eyes.\n\nYou quickly order the %companyname% to move on before this gets any worse. | For some reason, perhaps to sleep better at night, you order %randombrother% to hand out parcels of food. He's just getting started on the process when a villager quickly snatches a sack of foods. Another peasant stoves that man's head in and takes the sack for himself. This quickly erupts into a total free-for-all and your mercenaries have to draw weapons to protect the rest of the stores. By the end of the scuffle a few laymen lay dead and your brothers are a little marked up. Seeing no reason to hang around, you order the company to get back on the road. The leader who asked for your help is spotted in the distance, staring out at the horizon as a bitter wind curls his thin pantaloons about his shins.}",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{Goodness gets the better of you: you order %randombrother% to start handing out food. He complies, but as soon as he starts handing it out, the crowd goes nearly rabid, snatching it from one another. Fiery tempers are quickly fed by the air of empty bellies. The mercenary tries to maintain order, but anything he says only spurs the hungry masses into thinking it's all his fault. The violence spills over, ironically spilling all the food into the mud. Your brothers have to draw swords and by the end of it some peasants lay dead while the survivors look at the corpses with cannibalistic eyes.\\n\\nYou quickly order the %companyname% to move on before this gets any worse. | For some reason, perhaps to sleep better at night, you order %randombrother% to hand out parcels of food. He's just getting started on the process when a villager quickly snatches a sack of foods. Another peasant stoves that man's head in and takes the sack for himself. This quickly erupts into a total free-for-all and your mercenaries have to draw weapons to protect the rest of the stores. By the end of the scuffle a few laymen lay dead and your brothers are a little marked up. Seeing no reason to hang around, you order the company to get back on the road. The leader who asked for your help is spotted in the distance, staring out at the horizon as a bitter wind curls his thin pantaloons about his shins.}\""
    },
    {
        "key": "[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands clasped together.%SPEECH_ON%Please, would you help us? We have been without food for almost a week now. We're down to eating dirt! You have to understand, we have nothing! The war has ravaged us all.%SPEECH_OFF% | A small hamlet emerges beside your travels, little more than a cursory wink were it not for the large band of villagers standing outside seemingly awaiting you. Their leader steps forward.%SPEECH_ON%Mercenary, I know you are probably not the one to ask for this, but do you have any food to spare? The war has ravaged our crops and the soldiers that roam the land have taken what else there is to take! Please, help us!%SPEECH_OFF% | The roads lead you to a small hamlet. Villagers are squatting outside their hamlets, heads between their knees, looking thin and grey. Children are with them, frail and wiry, yet with the glow of youth still in their eyes. The town's leader comes to you personally.%SPEECH_ON%Sir... sellsword? Yes, sellsword. Please, we've been without food for a week now. We've been surviving on our pets, insects... even the dirt. Do you have anything to help us?%SPEECH_OFF% | As your men take a rest beside the road, villagers from a nearby hamlet come to you. They bumble forward, wiry legs shambling them from side to side. The head of the group raises and lowers a hand as though to bless your presence.%SPEECH_ON%Oh sellsword, mercenary, please, do you have anything to eat? We've yet to have a bite in two days! And what we have eaten are things not to be said aloud! The war between nobles has ruined this place, but maybe you can help?%SPEECH_OFF%}",
        "original": "[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands clasped together.%SPEECH_ON%Please, would you help us? We have been without food for almost a week now. We're down to eating dirt! You have to understand, we have nothing! The war has ravaged us all.%SPEECH_OFF% | A small hamlet emerges beside your travels, little more than a cursory wink were it not for the large band of villagers standing outside seemingly awaiting you. Their leader steps forward.%SPEECH_ON%Mercenary, I know you are probably not the one to ask for this, but do you have any food to spare? The war has ravaged our crops and the soldiers that roam the land have taken what else there is to take! Please, help us!%SPEECH_OFF% | The roads lead you to a small hamlet. Villagers are squatting outside their hamlets, heads between their knees, looking thin and grey. Children are with them, frail and wiry, yet with the glow of youth still in their eyes. The town's leader comes to you personally.%SPEECH_ON%Sir... sellsword? Yes, sellsword. Please, we've been without food for a week now. We've been surviving on our pets, insects... even the dirt. Do you have anything to help us?%SPEECH_OFF% | As your men take a rest beside the road, villagers from a nearby hamlet come to you. They bumble forward, wiry legs shambling them from side to side. The head of the group raises and lowers a hand as though to bless your presence.%SPEECH_ON%Oh sellsword, mercenary, please, do you have anything to eat? We've yet to have a bite in two days! And what we have eaten are things not to be said aloud! The war between nobles has ruined this place, but maybe you can help?%SPEECH_OFF%}",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_79.png[/img]{While traveling the roads, you come across a small hamlet with, apparently, it's entire populace standing outside. Their leader steps forward, hands out, pleading, though with hardly the strength to keep his hands clasped together.%SPEECH_ON%Please, would you help us? We have been without food for almost a week now. We're down to eating dirt! You have to understand, we have nothing! The war has ravaged us all.%SPEECH_OFF% | A small hamlet emerges beside your travels, little more than a cursory wink were it not for the large band of villagers standing outside seemingly awaiting you. Their leader steps forward.%SPEECH_ON%Mercenary, I know you are probably not the one to ask for this, but do you have any food to spare? The war has ravaged our crops and the soldiers that roam the land have taken what else there is to take! Please, help us!%SPEECH_OFF% | The roads lead you to a small hamlet. Villagers are squatting outside their hamlets, heads between their knees, looking thin and grey. Children are with them, frail and wiry, yet with the glow of youth still in their eyes. The town's leader comes to you personally.%SPEECH_ON%Sir... sellsword? Yes, sellsword. Please, we've been without food for a week now. We've been surviving on our pets, insects... even the dirt. Do you have anything to help us?%SPEECH_OFF% | As your men take a rest beside the road, villagers from a nearby hamlet come to you. They bumble forward, wiry legs shambling them from side to side. The head of the group raises and lowers a hand as though to bless your presence.%SPEECH_ON%Oh sellsword, mercenary, please, do you have anything to eat? We've yet to have a bite in two days! And what we have eaten are things not to be said aloud! The war between nobles has ruined this place, but maybe you can help?%SPEECH_OFF%}\""
    }
]