[
  {
    "ID": 293420863,
    "key": "{Always the adventurous type, %name% was easily drawn to the life of a caravan hand. | Orphaned by war and pestilence, %name% grew up under the wings of a traveling merchant. | A caravan hand's life is tough, but %name% could hardly stand staying in one p",
    "original": "{Always the adventurous type, %name% was easily drawn to the life of a caravan hand. | Orphaned by war and pestilence, %name% grew up under the wings of a traveling merchant. | A caravan hand's life is tough, but %name% could hardly stand staying in one place for too long. | Though the work is dangerous, being a caravan hand allowed %name% to see the world. | When his family and obligations were destroyed by fire, %name% saw no reason not to join a passing caravan. | Hardy and resolute, %name% was the first chosen by a merchant to protect his stock as a caravan hand. | Running away from home, it didn't long for %name% to join and eventually work for a caravan.} {But the trader he worked for turned out to be abusive, nary a whip away from being a slave driver. After an intense argument with the woman, %name% thought it better to leave before he did something awful. | One day, goods went missing and the hand was blamed for it, promptly ending his time with the caravan. | But a caravan needs protection for a reason, and an ambush by brigands proved why. %name% barely made it out alive. | Years on the road went without a hitch until a new caravan master refused to pay %name%. With just one hand the caravanner punched his boss and grabbed his wages. He used both legs to run, though. | Caravans are frequently tense places to be. One fateful evening, in a dispute over gambling debts, he stove in the head of another traveler. Fearing retribution, %name% was gone before morning. | Sadly, with the expanding war the caravan's profits were marginal. %name% was let go as the merchants retired their wagons. | After seeing the foul work of beasts on a fellow caravan, it didn't take long for %name% to figure out his wages didn't quite meet the level of threats around him. | But war deprived the caravan of stock and soon its driver took to selling slaves. Appalled, %name% freed as many as he could before leaving for good. | Sadly, his caravan began to sell human chattel. While the profits were enormous, it garnered the attention of a local militia - and their pitchforks. One ambush later and %name% was running for his life.} {Now uncertain of what to do, he seeks any opportunity that might come by. | A man like %name% is no stranger to danger, making him a good fit for any mercenary group. | With his caravan days behind him, working as a sellsword was just another avenue for adventure and profit. | In %name%'s mind, being a mercenary is a lot like being a caravanner. Just better paid. | Well versed to traveling, %name% seems like a natural fit to the tasks already befit for a mercenary. | Years of road travel have molded %name% into quite the durable figure. Any group of mercenaries could use more men like him.}",
    "translation": "{%name%一向是爱冒险的人，很容易被商队队员的生活所吸引。 | %name%因战争和瘟疫而成为孤儿，在一个商人的庇护下长大。 | 商队队员的生活是艰苦的，但%name%很难忍受在一个地方呆太久。 | 尽管工作很危险，但做一个商队队员可以让%name%见世面。 | 当他的家庭和责任被大火烧毁时，%name%觉得没有理由不加入路过的商队。 | %name%吃苦耐劳，意志坚定，是第一个被商人选来保护他货物的商队队员。 | %name%离家出走，没过多久就加入了一支商队，并最终在那里工作。}{但是他为之工作的商人最终被证明是个虐待狂，离奴隶贩子只差了一根鞭子。在与那个女人激烈争吵之后，%name%认为最好离开，以免自己做出可怕的事情。 | 有一天，货物不见了，这位商队队员因此受到指责，很快结束了他在商队的生活。 | 但商队需要保护是有原因的，一场强盗的伏击证明了这一点。%name%勉强活了下来。 | 几年的路途一帆风顺，直到一位新的商队老板拒绝支付克朗给%name%。这个商队队员只用一只手就打翻了老板夺回了他的工资。不过，他是用两条腿逃跑的。 | 商队经常是个令人神经紧张的地方。在一次有关赌债的争执中，他用炉子敲碎了另一名旅行者的头骨。为了防止报复，%name%在早晨离开了商队。 | 可悲的是，随着战争的扩大，商队的利润微乎其微。随着商人们的载重马车退役，%name%也被解雇了。 | 在看到野兽残杀同行商队队员的惨状后，很快%name%就意识到他的工资并不与他周围的威胁相匹配。 | 但是战争让商队损失了存货，很快商队头领就开始买卖奴隶了。%name%对此感到震惊，他在离开之前尽可能地解放了他能解放的奴隶。 | 可悲的是，他所在的商队开始出售人身动产（奴隶）。虽然获利颇丰，但这引起了当地民兵的注意 —— 以及他们的干草叉。一次伏击之后，%name%不得不逃命。}{现在他不知道该做什么，于是寻找任何可能出现的机会。 | 像%name%这样的人对危险并不陌生，这使他成为任何雇佣兵组织的合适人选。 | 随着他商队年华的过去，干佣兵的活计只是另一种冒险和赚钱的途径。 | 在%name%看来，当佣兵和在商队里干活很像。只是报酬更高。 | %name%在旅行方面很有经验，似乎天生就适合雇佣兵的任务。 | 多年行路把%name%塑造成了一个结实耐劳的人。任何佣兵团队都需要更多像他这样的人。}",
    "stage": 5,
    "context": "return \"{Always the adventurous type, %name% was easily drawn to the life of a caravan hand. | Orphaned by war and pestilence, %name% grew up under the wings of a traveling merchant. | A caravan hand's life is tough, but %name% could hardly stand staying in one place for too long. | Though the work is dangerous, being a caravan hand allowed %name% to see the world. | When his family and obligations were destroyed by fire, %name% saw no reason not to join a passing caravan. | Hardy and resolute, %name% was the first chosen by a merchant to protect his stock as a caravan hand. | Running away from home, it didn't long for %name% to join and eventually work for a caravan.} {But the trader he worked for turned out to be abusive, nary a whip away from being a slave driver. After an intense argument with the woman, %name% thought it better to leave before he did something awful. | One day, goods went missing and the hand was blamed for it, promptly ending his time with the caravan. | But a caravan needs protection for a reason, and an ambush by brigands proved why. %name% barely made it out alive. | Years on the road went without a hitch until a new caravan master refused to pay %name%. With just one hand the caravanner punched his boss and grabbed his wages. He used both legs to run, though. | Caravans are frequently tense places to be. One fateful evening, in a dispute over gambling debts, he stove in the head of another traveler. Fearing retribution, %name% was gone before morning. | Sadly, with the expanding war the caravan's profits were marginal. %name% was let go as the merchants retired their wagons. | After seeing the foul work of beasts on a fellow caravan, it didn't take long for %name% to figure out his wages didn't quite meet the level of threats around him. | But war deprived the caravan of stock and soon its driver took to selling slaves. Appalled, %name% freed as many as he could before leaving for good. | Sadly, his caravan began to sell human chattel. While the profits were enormous, it garnered the attention of a local militia - and their pitchforks. One ambush later and %name% was running for his life.} {Now uncertain of what to do, he seeks any opportunity that might come by. | A man like %name% is no stranger to danger, making him a good fit for any mercenary group. | With his caravan days behind him, working as a sellsword was just another avenue for adventure and profit. | In %name%'s mind, being a mercenary is a lot like being a caravanner. Just better paid. | Well versed to traveling, %name% seems like a natural fit to the tasks already befit for a mercenary. | Years of road travel have molded %name% into quite the durable figure. Any group of mercenaries could use more men like him.}\";"
  },
  {
    "ID": 293420864,
    "key": "%name% the once-caravan hand retired from fighting. He used his mercenary money to start a trade-guarding business that specializes in transporting goods through dangerous lands.",
    "original": "%name% the once-caravan hand retired from fighting. He used his mercenary money to start a trade-guarding business that specializes in transporting goods through dangerous lands.",
    "translation": "曾经的商队队员，%name%，从战斗生涯中退役了。他用自己当佣兵赚来的钱做起了押镖的生意，专门运送货物通过危险的地区。",
    "stage": 1,
    "context": "this.m.GoodEnding = '%name% the once-caravan hand retired from fighting. He used his mercenary money to start a trade-guarding business that specializes in transporting goods through dangerous lands.'"
  },
  {
    "ID": 293420865,
    "key": "Caravan hands are used to long and exhausting travels.",
    "original": "Caravan hands are used to long and exhausting travels.",
    "translation": "商队队员已经习惯了漫长而疲惫的旅行。",
    "stage": 5,
    "context": "this.m.BackgroundDescription = 'Caravan hands are used to long and exhausting travels.'"
  },
  {
    "ID": 293420866,
    "key": "%name% the caravan hand retired back into guarding trade wagons. He died when defending against an ambush by brigands. They took his shirt and left his body in a ditch.",
    "original": "%name% the caravan hand retired back into guarding trade wagons. He died when defending against an ambush by brigands. They took his shirt and left his body in a ditch.",
    "translation": "商队队员%name%退役后做回了护卫商队的工作。他在抵御强盗伏击时牺牲了。他们夺走了他的衣服，把他的尸体丢进了沟里。",
    "stage": 1,
    "context": "this.m.BadEnding = '%name% the caravan hand retired back into guarding trade wagons. He died when defending against an ambush by brigands. They took his shirt and left his body in a ditch.'"
  },
  {
    "ID": 293420867,
    "key": "Caravan Hand",
    "original": "Caravan Hand",
    "translation": "商队队员",
    "stage": 5,
    "context": "this.m.Name = 'Caravan Hand'"
  }
]
