[
  {
    "ID": 293420926,
    "key": "{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was litt",
    "original": "{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was little work to be a had these past weeks, so | %name% wanted to do something he had not done before, so | Despite having no experience in battle, staring too deep into the bottle made him believe that | %name% considered the fighting profession one that doesn't run out of work these days, so | %name% lost his loved one to sickness, as befalls so many these days, and broke down. After weeks blurred by drinking his sorrows away,} a travelling mercenary company seemed a good opportunity {to stay with for a while | to earn some coin | to see a bit of the world | to clear his head | to get him to the next village while filling his pockets}.",
    "translation": "{这儿干点那儿干点儿 | 没有稳定的工作 | 断断续续工作 | 做做这做做那 | 没有学过手艺}，%name%以日结工的身份为人所知，每当需要帮手时，大家都会想起他。{有一段时间没活干了， | 已经几周没什么活了， | %name%想做些以前没有做过的事情，  | 尽管没有战斗经验，脑袋里的酒精让他相信 | %name%估计最近不会缺干仗的活， | %name%的爱人因病逝去，就像最近发生在许多人身上的那样，他崩溃了。几个星期以来，他借酒消愁喝得烂醉如泥，}一个四处旅行的佣兵团似乎是个{可以跟着混一段时间 | 赚些钱 | 去看看这个世界 | 清醒一下头脑 | 能把钱袋子装满，顺便把他捎到下个村庄}的好机会。",
    "stage": 1,
    "context": "return \"{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was little work to be a had these past weeks, so | %name% wanted to do something he had not done before, so | Despite having no experience in battle, staring too deep into the bottle made him believe that | %name% considered the fighting profession one that doesn't run out of work these days, so | %name% lost his loved one to sickness, as befalls so many these days, and broke down. After weeks blurred by drinking his sorrows away,} a travelling mercenary company seemed a good opportunity {to stay with for a while | to earn some coin | to see a bit of the world | to clear his head | to get him to the next village while filling his pockets}.\";"
  },
  {
    "key": "e09f517cc9ea7ffee26777b07e27a696d5c44c319cd1fab7da0b201d0057c318",
    "original": "{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was little work to be had these past weeks, so | %name% wanted to do something he had not done before, so | Despite having no experience in battle, staring too deep into the bottle made him believe that | %name% considered the fighting profession one that doesn't run out of work these days, so | %name% lost his loved one to sickness, as befalls so many these days, and broke down. After weeks blurred by drinking his sorrows away,} a travelling mercenary company seemed a good opportunity {to stay with for a while | to earn some coin | to see a bit of the world | to clear his head | to get him to the next village while filling his pockets}.",
    "translation": "{四处打零工 | 没有固定工作 | 时断时续地工作 | 干这干那 | 没学过一门手艺}的%name%，被人们称为日工，每当需要额外人手时，大家都会找他。{最近工作机会稀少，所以 | 过去几周工作机会寥寥，所以 | %name%想尝试一些他从未做过的事情，所以 | 尽管没有战斗经验，但沉溺于酒精让他相信 | %name%认为战斗职业如今不会失业，所以 | %name%的爱人因病去世，这在如今屡见不鲜，他崩溃了。在借酒消愁的几周后，}加入一支四处游走的雇佣兵队伍似乎是个不错的选择{可以暂时落脚 | 能赚点钱 | 看看外面的世界 | 清醒一下头脑 | 既能填饱口袋，又能带他到下一个村庄}。"
  },
  {
    "key": "e09f517cc9ea7ffee26777b07e27a696d5c44c319cd1fab7da0b201d0057c318",
    "original": "{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was little work to be had these past weeks, so | %name% wanted to do something he had not done before, so | Despite having no experience in battle, staring too deep into the bottle made him believe that | %name% considered the fighting profession one that doesn't run out of work these days, so | %name% lost his loved one to sickness, as befalls so many these days, and broke down. After weeks blurred by drinking his sorrows away,} a travelling mercenary company seemed a good opportunity {to stay with for a while | to earn some coin | to see a bit of the world | to clear his head | to get him to the next village while filling his pockets}.",
    "translation": "{四处打零工 | 没有固定工作 | 时有时无地干活 | 做些零碎活儿 | 没学过什么手艺}的%name%，被人们称为临时工，每当需要额外人手时，总会有人想到他。{最近工作机会稀少，所以 | 过去几周几乎没什么活儿可干，所以 | %name%想尝试些以前没做过的事，所以 | 尽管没有战斗经验，但醉眼朦胧中他误以为自己能行，所以 | %name%认为如今战斗职业永远不会失业，所以 | %name%失去了心爱之人，如同许多人的遭遇，他崩溃了。借酒消愁几周后，}加入一支流动的雇佣兵队伍似乎是个不错的选择{暂时安顿下来 | 赚点钱 | 看看外面的世界 | 清醒一下头脑 | 既能前往下一个村庄，又能充实口袋}。",
    "context": "onBuildDescription = function onBuildDescription(){\n    return \"{Working here and there | With no steady work | Working on and off | Doing this and that | Having learned no craft}, %name% is known as a daytaler, someone to ask whenever an extra hand is needed. {Work had been sparse for a while now, so | There was little work to be had these past weeks, so | %name% wanted to do something he had not done before, so | Despite having no experience in battle, staring too deep into the bottle made him believe that | %name% considered the fighting profession one that doesn't run out of work these days, so | %name% lost his loved one to sickness, as befalls so many these days, and broke down. After weeks blurred by drinking his sorrows away,} a travelling mercenary company seemed a good opportunity {to stay with for a while | to earn some coin | to see a bit of the world | to clear his head | to get him to the next village while filling his pockets}.\";;\n    return;\n}"
  }
]
