[
  {
    "ID": 1007440859,
    "key": "20c3b6341bd628da946e003a156325e6d1a04a3c0508d58499acead6190899c7",
    "original": "A New Dawn, A New Path",
    "translation": "新的黎明，新的旅程",
    "stage": 1,
    "context": "this.m.Title = \"A New Dawn, A New Path\""
  },
  {
    "ID": 1007440860,
    "key": "7557b38f4019435a2f94466d4283b3a5ad0566e8fcbb4eb80aeb8b09466e7795",
    "original": "I embrace the life of a mercenary.",
    "translation": "拥抱佣兵的新生活。",
    "context": "Text = \"I embrace the life of a mercenary.\""
  },
  {
    "ID": 1007440861,
    "key": "396fd73ef49c92374ef1355903e9803624f494dc33b3b00b70ed76c965c235a6",
    "original": "[img]gfx/ui/events/rf_random_solo_intro.png[/img]The sun rises over the horizon, its light spilling across the muddy road beneath your boots. You've been walking for hours, maybe days, your mind heavy with thoughts of the life you've left behind. Whether you were a farmer, a soldier, a craftsman, or something else entirely, that life is gone now. The fields, the barracks, the workshop, they're all behind you. Ahead lies something uncertain, but it's yours to claim.\n\nYou pause, glancing down at the weapon at your side. It's not much but it's enough. You've heard the stories: mercenaries rising from nothing, carving out fortunes with steel and grit. You don't know if you believe them, but you're willing to find out. The world is harsh, and survival isn't guaranteed, but at least here, on this road, you have a chance to make your own way.\n\nThe sound of a passing cart breaks your thoughts. The driver eyes you warily before moving on. You don't blame him. You're just another stranger on the road, another soul trying to survive in a land torn by war and greed. But you know you're more than that. You have to be.\n\nYou think about what lies ahead. Coin, yes, but also something deeper. A purpose. A chance to build something that's yours. A company of your own, bound not by blood but by loyalty and shared struggle. It won't be easy, but nothing worth doing ever is.\n\nThe wind carries the faint scent of smoke and the distant clang of steel. Somewhere out there, battles are being fought, and fortunes are being made. You tighten your grip on your weapon and take a step forward. This is your path now. No turning back.\n\nThe road stretches ahead, endless and full of promise. You don't know where it will lead, but you know one thing: this is where your story begins. The past is behind you. The future is yours to seize.",
    "translation": "[img]gfx/ui/events/rf_random_solo_intro.png[/img]太阳从地平线上升起，把阳光洒在你脚下的泥土路上。你已经一连走了几个小时，也许是几天，过去的生活在你的脑海里挥之不去。无论你曾是农民，士兵还是工匠，或者其他什么身份，那些日子都已经一去不返了。田野，军营，工坊 ―― 远远地被你抛在了身后。前方会有什么并不确定，但你知道，它们正等着你去拿取。\n\n你停了停，低头看向身侧的武器。不算多精良，倒也还够用。你早就听过了这样的故事：一群佣兵白手起家，凭借钢铁和毅力创出了一片天地。你并不知道这样的故事是否可信，但你很愿意去一探究竟。世界是残酷的，你也未必能活下来，但至少走下去，你会开拓出自己的路。\n\n路过的马车声打断了你的思绪。车夫警醒的看了你一眼，然后继续走他的路。你并不怪他。对他来说，你不过是又一个陌生人，又一个在这片被战争和贪婪蹂躏的土地上谋生路的家伙罢了。但你知道你不会止步于此。你一定要成就一番事业。\n\n前方有什么东西等着你呢。钱？当然了，但应该不止于此。一份活下去的意义。一个建立属于自己的东西的机会。一个你自己的佣兵团，不是靠血缘维系，而是靠忠诚和共同奋斗联结在一起的佣兵团。这说不上容易，但有意义的事情从来就没有一蹴而就的。\n\n风中弥漫着淡淡的烟火味，和钢铁的铿锵声。在不远的某个地方，战斗正在进行，财富正被赚取。你握紧了武器，迈步前行。这正是你要走的路。一条没有退路的路。\n\n道路不断向前延伸，无尽且充满了希望。你不知道它会通向何方，但你知道的是，你的故事就是从这里开始。过去已经过去，未来在你掌握。",
    "context": "Text = \"[img]gfx/ui/events/rf_random_solo_intro.png[/img]The sun rises over the horizon, its light spilling across the muddy road beneath your boots. You've been walking for hours, maybe days, your mind heavy with thoughts of the life you've left behind. Whether you were a farmer, a soldier, a craftsman, or something else entirely, that life is gone now. The fields, the barracks, the workshop, they're all behind you. Ahead lies something uncertain, but it's yours to claim.\n\nYou pause, glancing down at the weapon at your side. It's not much but it's enough. You've heard the stories: mercenaries rising from nothing, carving out fortunes with steel and grit. You don't know if you believe them, but you're willing to find out. The world is harsh, and survival isn't guaranteed, but at least here, on this road, you have a chance to make your own way.\n\nThe sound of a passing cart breaks your thoughts. The driver eyes you warily before moving on. You don't blame him. You're just another stranger on the road, another soul trying to survive in a land torn by war and greed. But you know you're more than that. You have to be.\n\nYou think about what lies ahead. Coin, yes, but also something deeper. A purpose. A chance to build something that's yours. A company of your own, bound not by blood but by loyalty and shared struggle. It won't be easy, but nothing worth doing ever is.\n\nThe wind carries the faint scent of smoke and the distant clang of steel. Somewhere out there, battles are being fought, and fortunes are being made. You tighten your grip on your weapon and take a step forward. This is your path now. No turning back.\n\nThe road stretches ahead, endless and full of promise. You don't know where it will lead, but you know one thing: this is where your story begins. The past is behind you. The future is yours to seize.\""
  }
]
