[
  {
    "ID": 293404745,
    "key": "BATTLE BROTHERS\n\n\nDEVELOPED BY\nOverhype Studios\n\n\nBATTLE BROTHERS DEVELOPMENT TEAM\n\n\nGAME DESIGN\nChristof Schmidt\nJan Taaks\nPaul Taaks\n\n\nART\nPaul Taaks\n\n\nPROGRAMMING\nChristof Schmidt\n\n\nADDITIONAL PROGRAMMING\nJesse Cooper\n\n\nPRODUCTION\nJan Taaks\n\n\nWRITING\nC",
    "original": "BATTLE BROTHERS\n\n\nDEVELOPED BY\nOverhype Studios\n\n\nBATTLE BROTHERS DEVELOPMENT TEAM\n\n\nGAME DESIGN\nChristof Schmidt\nJan Taaks\nPaul Taaks\n\n\nART\nPaul Taaks\n\n\nPROGRAMMING\nChristof Schmidt\n\n\nADDITIONAL PROGRAMMING\nJesse Cooper\n\n\nPRODUCTION\nJan Taaks\n\n\nWRITING\nCasey Hollingshead\n\n\nADDITIONAL WRITING\nChristof Schmidt\nScott Hamm\n\n\nMUSIC\nPatrick Delaney (Breakdown Epiphanies)\nDennis Meyer (Breakdown Epiphanies)\n\n\nSOUND DESIGN\nMorten Barfod Soegaard (MBS Sounddesign)\nTroels Kristensen (AudioNation ApS)\n\n\nADDITIONAL SOUND DESIGN\nLucien McRobbie\nMichael Klier\nBreakdown Epiphanies\nJan Taaks\n\n\nTRAILER VIDEOS\nMarlon Wiebe\nJaleo PR\nBreakdown Epiphanies\n\n\nSPECIAL THANKS FROM THE DEVELOPMENT TEAM TO\nOur girlfriends and wives for their support throughout the years of development\nJochen Taaks\nAbel aka Vilain Joueur\nHeron\nJC Sato\nJoachim 'Lovegun' Roderfeld\nJohan Nagstrup\nKrzysztof Kielczewski\nMarius Ovidiu Voinescu\nSimone Bucciarelli (They Live)\nsuejak\nS. Quartermaine\nTrappist\nturtle225\nVasilisa 'Dialetheia' Prince\nWillsama974\nThomas Fischer and the team at BeamNG\nTyler Sigman from Red Hook Studios\nTom Giardino and the Steam team at Valve\nAll of our dedicated Early Access players for their support and feedback\nThe RPG Codex crowd\n\n\n\n\nBATTLE BROTHERS\nCopyright 2015 - 2022 Overhype Studios UG\nAll rights reserved",
    "translation": "战场兄弟\n\n开发团队\nOverhype Studios\n\n战场兄弟开发团队\n\n游戏设计\nChristof Schmidt\nJan Taaks\nPaul Taaks\n\n艺术设计\nPaul Taaks\n\n编程\nChristof Schmidt\n\n额外编程\nJesse Cooper\n\n制作\nJan Taaks\n\n编剧\nCasey Hollingshead\n\n额外编剧\nChristof Schmidt\nScott Hamm\n\n音乐\nPatrick Delaney (Breakdown Epiphanies)\nDennis Meyer (Breakdown Epiphanies)\n\n音效设计\nMorten Barfod Soegaard (MBS Sounddesign)\nTroels Kristensen (AudioNation ApS)\n\n额外音效设计\nLucien McRobbie\nMichael Klier\nBreakdown Epiphanies\nJan Taaks\n\n预告片制作\nMarlon Wiebe\nJaleo PR\nBreakdown Epiphanies\n\n\n特别感谢\n我们的女友和妻子在开发的这些年里一直的支持\nJochen Taaks\nAbel aka Vilain Joueur\nHeron\nJC Sato\nJoachim 'Lovegun' Roderfeld\nJohan Nagstrup\nKrzysztof Kielczewski\nMarius Ovidiu Voinescu\nSimone Bucciarelli (They Live)\nsuejak\nS. Quartermaine\nTrappist\nturtle225\nVasilisa 'Dialetheia' Prince\nWillsama974\nThomas Fischer 以及 BeamNG 团队\n来自 Red Hook Studios 的 Tyler Sigman\nTom Giardino 以及 Valve 的 Steam 团队\n我们所有投入的抢先体验玩家以及他们的支持和反馈\nRPG Codex众筹支持团队\n\n战场兄弟\nCopyright 2015 - 2022 Overhype Studios UG\nAll rights reserved",
    "stage": 1,
    "context": "gt.Const.Credits = \"BATTLE BROTHERS\n\n\nDEVELOPED BY\nOverhype Studios\n\n\nBATTLE BROTHERS DEVELOPMENT TEAM\n\n\nGAME DESIGN\nChristof Schmidt\nJan Taaks\nPaul Taaks\n\n\nART\nPaul Taaks\n\n\nPROGRAMMING\nChristof Schmidt\n\n\nADDITIONAL PROGRAMMING\nJesse Cooper\n\n\nPRODUCTION\nJan Taaks\n\n\nWRITING\nCasey Hollingshead\n\n\nADDITIONAL WRITING\nChristof Schmidt\nScott Hamm\n\n\nMUSIC\nPatrick Delaney (Breakdown Epiphanies)\nDennis Meyer (Breakdown Epiphanies)\n\n\nSOUND DESIGN\nMorten Barfod Soegaard (MBS Sounddesign)\nTroels Kristensen (AudioNation ApS)\n\n\nADDITIONAL SOUND DESIGN\nLucien McRobbie\nMichael Klier\nBreakdown Epiphanies\nJan Taaks\n\n\nTRAILER VIDEOS\nMarlon Wiebe\nJaleo PR\nBreakdown Epiphanies\n\n\nSPECIAL THANKS FROM THE DEVELOPMENT TEAM TO\nOur girlfriends and wives for their support throughout the years of development\nJochen Taaks\nAbel aka Vilain Joueur\nHeron\nJC Sato\nJoachim 'Lovegun' Roderfeld\nJohan Nagstrup\nKrzysztof Kielczewski\nMarius Ovidiu Voinescu\nSimone Bucciarelli (They Live)\nsuejak\nS. Quartermaine\nTrappist\nturtle225\nVasilisa 'Dialetheia' Prince\nWillsama974\nThomas Fischer and the team at BeamNG\nTyler Sigman from Red Hook Studios\nTom Giardino and the Steam team at Valve\nAll of our dedicated Early Access players for their support and feedback\nThe RPG Codex crowd\n\n\n\n\nBATTLE BROTHERS\nCopyright 2015 - 2022 Overhype Studios UG\nAll rights reserved\""
  }
]
