[
    {
        "ID": 293415756,
        "key": "[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your me",
        "original": "[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your men a tray of refreshments. %randombrother% slams a few mugs down as a dainty, girlish server looks on in awe. He wipes his mouth.%SPEECH_ON%Appreciated. More, please.%SPEECH_OFF% | Business in %townname% has been good and the people there seem to appreciate you more and more: on today's arrival they gave you {plenty of useless thanks | a storm of gratitude | flowers upon flowers which you have no use for | trinkets and other things that you throw away when the peasants aren't looking | a tray of ale which your men quickly consume | a cask of ale which your men tactlessly criticize as 'tasting wooden' | a few marriage proposals which you gracefully turn down | a few marriage proposals which you can't turn down fast enough | one marriage proposal from the town ugly. She has a face that could stop a sundial. You decline the offer | a quick celebration wherein a few people shouted incoherently. Their tone seemed cheery, anyway | a few slaps on the back. You reminded them that such a doing might leave them handless on the next go around | an offering of orphans. You've no idea what gave them the notion that you'd accept such a gift, but you return the children to their sad home, also known as the streets}.}",
        "translation": "[img]gfx/ui/events/event_85.png[/img]{你到达 %townname% 大概是为了庆祝一下。 镇上的一位议员向你问好，提供点心。 | %townname% 对你照顾他们的生意表示了感谢，因此他们为你的队员们献上了一些点心。%randombrother% 碰掉了几个杯子，年轻的女服务员被吓坏了。 他擦了擦嘴。%SPEECH_ON%谢谢啊。请再来点。%SPEECH_OFF% | %townname% 的生意一直很好，而那里的人似乎越来越感激你：今天你们的到来，他们给予你 { 大量无用的口头感谢 | 暴风雨般的称颂 | 一大堆对你来说没啥用鲜花 | 你平时会扔掉的那种小饰品和其他东西，因为就算农民们都看不上 | 一盘被你的队员们迅速干掉的啤酒 | 一桶被你的队员们口无遮拦的批评为“木头味道”的啤酒， | 几个你会求婚，被你的优雅地拒绝 | a few marriage proposals which you can't turn down fast enough | 一个丑女村妇的求婚。她的脸能挡住日晷，所以你必然拒绝 | 一场语无伦次的表演，虽然他们的语气似乎很愉快 | 后背几个大巴掌. 你提醒他们下次这么干可能会被剁手 | 送你一些孤儿。 你不知道是什么让他们产生了你会接受这样一份礼物的想法，总之你把孩子们送回了他们悲伤的家 -- 也被称为街道}。}",
        "stage": 1,
        "context": "Text = \"[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your men a tray of refreshments. %randombrother% slams a few mugs down as a dainty, girlish server looks on in awe. He wipes his mouth.%SPEECH_ON%Appreciated. More, please.%SPEECH_OFF% | Business in %townname% has been good and the people there seem to appreciate you more and more: on today's arrival they gave you {plenty of useless thanks | a storm of gratitude | flowers upon flowers which you have no use for | trinkets and other things that you throw away when the peasants aren't looking | a tray of ale which your men quickly consume | a cask of ale which your men tactlessly criticize as 'tasting wooden' | a few marriage proposals which you gracefully turn down | a few marriage proposals which you can't turn down fast enough | one marriage proposal from the town ugly. She has a face that could stop a sundial. You decline the offer | a quick celebration wherein a few people shouted incoherently. Their tone seemed cheery, anyway | a few slaps on the back. You reminded them that such a doing might leave them handless on the next go around | an offering of orphans. You've no idea what gave them the notion that you'd accept such a gift, but you return the children to their sad home, also known as the streets}.}\""
    },
    {
        "ID": 293415757,
        "key": "Always nice to be in %townname%.",
        "original": "Always nice to be in %townname%.",
        "translation": "总是很高兴在 %townname%。",
        "stage": 1,
        "context": "Text = 'Always nice to be in %townname%.'"
    },
    {
        "ID": 293415758,
        "key": "At %townname%",
        "original": "At %townname%",
        "translation": "在%townname%",
        "stage": 1,
        "context": "this.m.Title = 'At %townname%'"
    },
    {
        "key": "[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your men a tray of refreshments. %randombrother% slams a few mugs down as a dainty, girlish server looks on in awe. He wipes his mouth.%SPEECH_ON%Appreciated. More, please.%SPEECH_OFF% | Business in %townname% has been good and the people there seem to appreciate you more and more: on today's arrival they gave you {plenty of useless thanks | a storm of gratitude | flowers upon flowers which you have no use for | trinkets and other things that you throw away when the peasants aren't looking | a tray of ale which your men quickly consume | a cask of ale which your men tactlessly criticize as 'tasting wooden' | a few marriage proposals which you gracefully turn down | a few marriage proposals which you can't turn down fast enough | one marriage proposal from the town ugly. She has a face that could stop a sundial. You decline the offer | a quick celebration wherein a few people shouted incoherently. Their tone seemed cheery, anyway | a few slaps on the back. You reminded them that such a doing might leave them handless on the next go around | an offering of orphans. You've no idea what gave them the notion that you'd accept such a gift, but you return the children to their sad home, also known as the streets}.}",
        "original": "[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your men a tray of refreshments. %randombrother% slams a few mugs down as a dainty, girlish server looks on in awe. He wipes his mouth.%SPEECH_ON%Appreciated. More, please.%SPEECH_OFF% | Business in %townname% has been good and the people there seem to appreciate you more and more: on today's arrival they gave you {plenty of useless thanks | a storm of gratitude | flowers upon flowers which you have no use for | trinkets and other things that you throw away when the peasants aren't looking | a tray of ale which your men quickly consume | a cask of ale which your men tactlessly criticize as 'tasting wooden' | a few marriage proposals which you gracefully turn down | a few marriage proposals which you can't turn down fast enough | one marriage proposal from the town ugly. She has a face that could stop a sundial. You decline the offer | a quick celebration wherein a few people shouted incoherently. Their tone seemed cheery, anyway | a few slaps on the back. You reminded them that such a doing might leave them handless on the next go around | an offering of orphans. You've no idea what gave them the notion that you'd accept such a gift, but you return the children to their sad home, also known as the streets}.}",
        "translation": "",
        "context": "Text = \"[img]gfx/ui/events/event_85.png[/img]{Your arrival in %townname% seems to be cause for some celebration. One of the town's councilman greets you, offering refreshments. | %townname% shows its appreciation for your business there by handing you and your men a tray of refreshments. %randombrother% slams a few mugs down as a dainty, girlish server looks on in awe. He wipes his mouth.%SPEECH_ON%Appreciated. More, please.%SPEECH_OFF% | Business in %townname% has been good and the people there seem to appreciate you more and more: on today's arrival they gave you {plenty of useless thanks | a storm of gratitude | flowers upon flowers which you have no use for | trinkets and other things that you throw away when the peasants aren't looking | a tray of ale which your men quickly consume | a cask of ale which your men tactlessly criticize as 'tasting wooden' | a few marriage proposals which you gracefully turn down | a few marriage proposals which you can't turn down fast enough | one marriage proposal from the town ugly. She has a face that could stop a sundial. You decline the offer | a quick celebration wherein a few people shouted incoherently. Their tone seemed cheery, anyway | a few slaps on the back. You reminded them that such a doing might leave them handless on the next go around | an offering of orphans. You've no idea what gave them the notion that you'd accept such a gift, but you return the children to their sad home, also known as the streets}.}\""
    }
]