[
  {
    "key": "1f1b8deaf876a9e0b37464f3a4181fc449364378095fb6adb35a1c8ab00ccc67",
    "original": "At %townname%",
    "translation": "",
    "context": "this.m.Title = \"At %townname%\""
  },
  {
    "key": "fca65e40594876e676d2e5a05f83896ce69db7d1d325c44974fbdcad6e1a6d70",
    "original": "War is upon us.",
    "translation": "",
    "context": "Text = \"War is upon us.\""
  },
  {
    "key": "55a8f433dfa4058ed8a311efb995d22aed5fe4b3bc3ea2037affbfc15bc56766",
    "original": "[img]gfx/ui/events/event_92.png[/img]You enter %townname% and find a group of laymen standing around a wooden platform. Thinking there's a hanging to be seen, you quickly push through the crowd. What you find instead is a queerly dressed man barking out news to the townsfolk.%SPEECH_ON%Harken harken harken, a determination has been made between the noble houses %noblehouse1% and %noblehouse2%! They have come to a conclusion all sides can agree upon: they hate one another!%SPEECH_OFF%Nervous whispers wrinkle the crowd. As the volume builds, the whispers crescendo into hushes. The minstrel continues.%SPEECH_ON%That is right, my fair fair-folk! War is upon us! Ah yes, that fickle beast which lies dormant in all men. A sad affair, a righteous affair, an honorable one!%SPEECH_OFF%An old man standing in front of you grumbles and spits. He leaves, shaking his head and murmuring to himself. The minstrel presses on, his excitement not matching the terrified faces before him.%SPEECH_ON%Let us not dawdle on ceremony. I've been instructed to speak thusly: men, take up arms where you can, plough the fields while you can't. Women, raise yer sons right, lest they may raise a sword all wrong!%SPEECH_OFF%Finally, the minstrel takes a great big breath.%SPEECH_ON%And those among you who wish to earn a good crown or two, the noble houses are looking for the fine services of any man who can swing a sword. Those among you of lesser honor, you bridle-loosers, bride-stealers, leech-sellers, smellsmocks, ne'er do wells, vice obsessed and run amuck, brigands, bandits, and thieving graduates, you sickly and poison moistened, the cursed and rabid, the cured and vapid, sellswords and poets selling words, this, my fine genteel men, is YOUR time. Go out there, fight for the nobles, and earn yourself a new life! A shame that a war shan't last forever, so best do it quick!%SPEECH_OFF%It looks as though the %companyname%'s future just got brighter - on account of the loads of gold you're about to be earning.",
    "translation": "",
    "context": "Text = \"[img]gfx/ui/events/event_92.png[/img]You enter %townname% and find a group of laymen standing around a wooden platform. Thinking there's a hanging to be seen, you quickly push through the crowd. What you find instead is a queerly dressed man barking out news to the townsfolk.%SPEECH_ON%Harken harken harken, a determination has been made between the noble houses %noblehouse1% and %noblehouse2%! They have come to a conclusion all sides can agree upon: they hate one another!%SPEECH_OFF%Nervous whispers wrinkle the crowd. As the volume builds, the whispers crescendo into hushes. The minstrel continues.%SPEECH_ON%That is right, my fair fair-folk! War is upon us! Ah yes, that fickle beast which lies dormant in all men. A sad affair, a righteous affair, an honorable one!%SPEECH_OFF%An old man standing in front of you grumbles and spits. He leaves, shaking his head and murmuring to himself. The minstrel presses on, his excitement not matching the terrified faces before him.%SPEECH_ON%Let us not dawdle on ceremony. I've been instructed to speak thusly: men, take up arms where you can, plough the fields while you can't. Women, raise yer sons right, lest they may raise a sword all wrong!%SPEECH_OFF%Finally, the minstrel takes a great big breath.%SPEECH_ON%And those among you who wish to earn a good crown or two, the noble houses are looking for the fine services of any man who can swing a sword. Those among you of lesser honor, you bridle-loosers, bride-stealers, leech-sellers, smellsmocks, ne'er do wells, vice obsessed and run amuck, brigands, bandits, and thieving graduates, you sickly and poison moistened, the cursed and rabid, the cured and vapid, sellswords and poets selling words, this, my fine genteel men, is YOUR time. Go out there, fight for the nobles, and earn yourself a new life! A shame that a war shan't last forever, so best do it quick!%SPEECH_OFF%It looks as though the %companyname%'s future just got brighter - on account of the loads of gold you're about to be earning.\""
  }
]