[
  {
    "key": "eb383fcf15b30260c90f3fa460f551c7117f59048bc273743b0c787f1b68cec5",
    "original": " days in total without at least ",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "46b0b54ad0594ae1fbc9c134ecc7d1bee60b937bb5d238b0c485324bdc0a9709",
    "original": " in battle.\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\n- Character backgrounds highly proficient in melee combat are not recruitable.\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\n- Named weapon drops from locations are more likely to be swords.",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "120e8e083b6915f86ba08cc0a76f8ef56b98dcc65f838f7b20559df8e386db22",
    "original": " other recruits.\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\n- Recruits with access to the Sword perk group have a ",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "c5a6e1fbbfb5ea022d910d443143ff0b1e183ae95b800abf6c65446a78e6ecd4",
    "original": " total characters and maximum ",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "31abb556d67cd9360c6e2f6f36823b81759cdad644c0319352a72b4658b1dc51",
    "original": "% chance to gain a free sword perk upon leveling up.\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\n- Limited to ",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "9d00294091a0d717c5967f8efda27524e38150a088b58c596d9fc011dbcc9153",
    "original": "%OOC%How this origin works:%OOC_OFF%\n- It's all about teaching your students. The game will end if you spend ",
    "translation": "",
    "context": "\"%OOC%How this origin works:%OOC_OFF%\\n- It's all about teaching your students. The game will end if you spend \" + avatarEffect.m.DaysWithoutRecruitsMax + \" days in total without at least \" + avatarEffect.m.NumRecruitsRequired - 1 + \" other recruits.\\n- Recruits gain the 'Swordmaster's Training' effect which grants special bonuses when using swords and gets stronger with every level.\\n- Recruits with access to the Sword perk group have a \" + recruitEffect.m.FreePerkChancePerLevel + \"% chance to gain a free sword perk upon leveling up.\\n- Recruits who come with access to the Sword perk group lose all other weapon perk groups and gain access to the Swordmaster perk group with special perks related to swordfighting to allow for a variety of different specializations and fighting styles.\\n- Cannot equip any weapon except swords, banner, or a ranged weapon.\\n- Remember to check the tooltip of the 'Swordmaster's Training' or 'Swordmaster's Finesse' effects on your characters for important information regarding their bonuses (and penalties if applicable).\\n- Limited to \" + origin.m.BrothersMax + \" total characters and maximum \" + origin.m.BrothersMaxInCombat + \" in battle.\\n- The main character will get exhausted after every battle and will need a few days to get back in fighting shape. He will also get older over time and get various penalties.\\n- Highly talented recruits can challenge swordmasters at settlements, and if successful, gain strong bonuses.\\n- Character backgrounds highly proficient in melee combat are not recruitable.\\n- The world tests your steel without restraint. Combat difficulty scales faster in this origin than usual, resulting in contracts being more deadly.\\n- The Fountain of Youth (Grotesque Tree) location does not exist in this origin.\\n- Named weapon drops from locations are more likely to be swords.\""
  },
  {
    "key": "2d5aa18044924b0f2e34e17061b3be4b7270a473c519315592deccb11167ca58",
    "original": "It is time...",
    "translation": "",
    "context": "Text = \"It is time...\""
  },
  {
    "key": "903e4e87d7d754642a0c5b606423ee67855582188e4430f94db234f6965590d4",
    "original": "Origin Description",
    "translation": "",
    "context": "_event.m.Title = \"Origin Description\""
  },
  {
    "key": "7dae5272a2540f1ca9f7de775b0e8475252cb409eb355dd3a1df2a20e027ca9c",
    "original": "Removing the Fountain of Youth (Grotesque Tree) location",
    "translation": "",
    "context": ""
  },
  {
    "key": "e67e9b4d55cfbb418566c85293a3c1b4a12b94fd41eabae6e3940a8406aaf785",
    "original": "The Last Lesson",
    "translation": "",
    "context": "this.m.Title = \"The Last Lesson\""
  },
  {
    "key": "57427e6f4ab9af0cee31a15acd8ddeaeba2840949e76a5ca389ba7b783d047c8",
    "original": "[img]gfx/ui/events/event_17.png[/img]The candle’s flame wavered in the draft, casting long shadows against the rough-hewn walls of your cabin. This place, nestled on the edge of the wild forest, has been your sanctuary for decades. Here, you honed your craft, shaping your body into a weapon and your mind into a whetstone. The sword has been your sole companion—a silent partner in battles fought and victories claimed. Yet now, as the twilight of your life closes in, you find yourself not thinking of wars or triumphs, but of silence—the silence that will follow you when you are gone.\n\nIt’s a peculiar thing, the passage of time. The strength in your arms, once unyielding, now falters. Your once-steady hands quiver, though the spirit within them still burns. And with every creak of these old bones, you feel the weight of a lifetime of knowledge—knowledge that will vanish like morning mist if left unshared. The art of the sword is not merely a dance of steel; it is a philosophy, a discipline, a way of seeing the world. It is the rhythm of breath in chaos, the calm at the heart of the storm. It has shaped you, but what worth is it if it shapes no one else?\n\nThere must be someone out there—a seeker, a wanderer, perhaps even a fool—worthy of this craft. You think back to the wonder and excitement you felt when you first took up the sword, the thrill of discovery in every lesson, and the awe of realizing how much there was to learn. That same spark must exist in someone now, someone who can take what you’ve spent a lifetime mastering and carry it forward, refining it, living it, teaching it.\n\nAnd so, you resolve to teach. Not to preserve your name, for names are fleeting, but to give this knowledge a life beyond your own. The way of the sword is not yours to keep; it is a river, flowing from one hand to the next. You will seek those who are willing to learn. The silence you shall leave behind will not be empty, but filled with the echoes of steel meeting steel, of wisdom passed from master to student.\n\nThe candle burns low, yet its light is enough to guide you. And as you rise, your sword resting against the wall like an old friend, you feel a strange sense of hope. Your life is no longer just your own; it is a bridge to those who will come after. Let them come. You will teach them all you know.",
    "translation": "",
    "context": "Text = \"[img]gfx/ui/events/event_17.png[/img]The candle\\u2019s flame wavered in the draft, casting long shadows against the rough-hewn walls of your cabin. This place, nestled on the edge of the wild forest, has been your sanctuary for decades. Here, you honed your craft, shaping your body into a weapon and your mind into a whetstone. The sword has been your sole companion\\u2014a silent partner in battles fought and victories claimed. Yet now, as the twilight of your life closes in, you find yourself not thinking of wars or triumphs, but of silence\\u2014the silence that will follow you when you are gone.\\n\\nIt\\u2019s a peculiar thing, the passage of time. The strength in your arms, once unyielding, now falters. Your once-steady hands quiver, though the spirit within them still burns. And with every creak of these old bones, you feel the weight of a lifetime of knowledge\\u2014knowledge that will vanish like morning mist if left unshared. The art of the sword is not merely a dance of steel; it is a philosophy, a discipline, a way of seeing the world. It is the rhythm of breath in chaos, the calm at the heart of the storm. It has shaped you, but what worth is it if it shapes no one else?\\n\\nThere must be someone out there\\u2014a seeker, a wanderer, perhaps even a fool\\u2014worthy of this craft. You think back to the wonder and excitement you felt when you first took up the sword, the thrill of discovery in every lesson, and the awe of realizing how much there was to learn. That same spark must exist in someone now, someone who can take what you\\u2019ve spent a lifetime mastering and carry it forward, refining it, living it, teaching it.\\n\\nAnd so, you resolve to teach. Not to preserve your name, for names are fleeting, but to give this knowledge a life beyond your own. The way of the sword is not yours to keep; it is a river, flowing from one hand to the next. You will seek those who are willing to learn. The silence you shall leave behind will not be empty, but filled with the echoes of steel meeting steel, of wisdom passed from master to student.\\n\\nThe candle burns low, yet its light is enough to guide you. And as you rise, your sword resting against the wall like an old friend, you feel a strange sense of hope. Your life is no longer just your own; it is a bridge to those who will come after. Let them come. You will teach them all you know.\""
  }
]