[
  {
    "ID": 293416876,
    "key": "{Not everything goes as planned. | Oh well. | The men will understand. | This won't stop the %companyname%. | The important thing is that we're moving forward. | New challenges await.}",
    "original": "{Not everything goes as planned. | Oh well. | The men will understand. | This won't stop the %companyname%. | The important thing is that we're moving forward. | New challenges await.}",
    "translation": "{并不是所有的事情都按照计划进行。 | 噢，好吧。 | 人们会理解的。 | 这不会阻止 %companyname%。 | 重要的是我们要继续前进。 | 新的挑战等着我们。}",
    "stage": 1,
    "context": "Text = \"{Not everything goes as planned. | Oh well. | The men will understand. | This won't stop the %companyname%. | The important thing is that we're moving forward. | New challenges await.}\""
  },
  {
    "ID": 293416877,
    "key": "[img]gfx/ui/events/event_64.png[/img]{%randombrother% grumbles.%SPEECH_ON%Giving up is not the way of this company, or at least I didn't think it was.%SPEECH_OFF%The men have been moping about today, cursing loudly about nothing and muttering into their d",
    "original": "[img]gfx/ui/events/event_64.png[/img]{%randombrother% grumbles.%SPEECH_ON%Giving up is not the way of this company, or at least I didn't think it was.%SPEECH_OFF%The men have been moping about today, cursing loudly about nothing and muttering into their drink. They are unhappy about the company not achieving the goal everyone agreed on.%SPEECH_ON%Certainly we could chase this task we set ourselves across the world and back, just as we could spend our days chasing butterflies, but if it cannot be done let's put this misfortune behind us and move on to what we do best: fighting, drinking, and spending our hard-earned coin!%SPEECH_OFF%%highestexperience_brother% encourages his brothers-in-arms. These words placate the men somewhat and you are relieved not to have a revolt on your hands. | As you walk around the tents of the camp, %randombrother% approaches to complain.%SPEECH_ON%I seem to recall signing up with a band of merciless fighting men. Men who let nothing stand in their path. Now the %companyname% feels more like a squad of tired children than an unstoppable force.%SPEECH_OFF%He pauses, bites his lips.%SPEECH_ON%Captain, sir, I mean.%SPEECH_OFF%You nod and continue on your way. Clearly, the man is upset about the company's inability to fulfill the goal you announced to the men not long ago. | Despite your best efforts, you failed in fulfilling your latest ambition on the company's path to greatness. Worse, the men are all keenly aware of it, and seem more put out by this failure than you are. Feet are dragging, heads hanging, and griping and discontent louder than usual.\n\nStill, the sun rises just the same, and to worry over one's failures is to waste time better spent on new opportunities. You know that the men of the %companyname% will ride out this setback and march on to greater glories. Or die in the attempt. | After much striving and effort, you are finally forced to give up on the ambition you chose for the %companyname% to pursue. A mercenary company must face many setbacks on the road to greatness, but this latest failure to follow through has been especially bitter for the men. It would be wise to secure a lucrative contract or provide some other distraction, perhaps the threat of imminent death, to distract them from their unhappiness. | After you tell the men that the company isn't going to be able to do what you so proudly announced it would accomplish, the men grow standoffish and moody. Like sulky children they turn away when you come near and whisper their complaints whenever your back is turned.%SPEECH_ON%How are we ever going to be famous if we don't finish what we started? I want to be known wherever we go, and have our drinks poured before we walk in the door.%SPEECH_OFF%}",
    "translation": "[img]gfx/ui/events/event_64.png[/img]{%randombrother% 抱怨。%SPEECH_ON%放弃从不是我们战团的作风，或者说至少我认为不是。%SPEECH_OFF%团中的人们今天一直闷闷不乐，一边喝酒一边不知道咒骂着什么。 他们对战团没有达到每个人都认同的目标而不高兴。%SPEECH_ON%当然我们可以一直追寻着这项我们设定的任务跑遍整个世界，就像我们花费一整天的时间抓蝴蝶一样，但是如果这件事完成不了就让我们将这件不幸的事情抛在我们的身后然后向前进做我们最擅长的事情：打架，喝酒，还有随意挥霍我们的血汗钱！%SPEECH_OFF%%highestexperience_brother% 鼓励着他手臂搭着的战友。 这些话语给了人们几分安抚，并且你也庆幸没有在你身边发生哗变。 | 正当你在营地帐篷旁边走动的时候，%randombrother% 接近你并抱怨。%SPEECH_ON%在我的记忆中和我签约的是一群无情的战士。 他们不会让任何东西阻挡他们前进的道路。 现在 %companyname% 让人感觉更像是一群累了的孩子而不是一股无法阻挡的力量。%SPEECH_OFF%他停顿了一下，咬着嘴唇。%SPEECH_ON%队长，我的意思是。%SPEECH_OFF%你点了点头并继续向前走着。 很明显，这个男人对于战团没能实现你不久前向他们宣布的目标感到沮丧。 | 尽管你尽了最大的努力，你还是没能在战团通往成功的道路上实现你们最近的目标。 更加糟糕的是，团队中的人们都敏锐地意识到了这一点，他们似乎比你更在意这次失败。 双脚拖着地，脑袋耷拉着，满腹牢骚，不满的声音比平时更大。\n\n尽管如此，太阳照常升起，把心思都用在担心之前的一场失败上就是在浪费时间不如用这些时间去追寻新的目标。 你知道 %companyname% 的战士们将会安然度过这次挫折并且走向更伟大的辉煌。 或者死在尝试的路上。 | 经过了许多的努力和尝试，你最终还是放弃了你为 %companyname% 所选择的目标。 一个雇佣兵战团在走向伟大的道路上必须面对许多挫折，但最近的一次失败对这些人来说尤其痛苦。 明智的做法是获得一份利润丰厚的合同或者提供一些其他分散注意力的东西，比如一次迫在眉睫的死亡威胁，用来分散他们的注意力。 | 当你告诉他们，战团不能做到你自豪的宣布的事情后，他们变得泠漠和喜怒无常。 当你走近他们时，他们像生气的孩子一样转过身去，当你转身时，他们又低声抱怨。%SPEECH_ON%如果我们不能完成我们开始的事情，我们要如何出名？ 无论我们走到哪里，我都想让别人知道我们，并且我想让所有地方在我们进门之前就帮我们把饮品倒上。%SPEECH_OFF%}",
    "stage": 1,
    "context": "Text = \"[img]gfx/ui/events/event_64.png[/img]{%randombrother% grumbles.%SPEECH_ON%Giving up is not the way of this company, or at least I didn't think it was.%SPEECH_OFF%The men have been moping about today, cursing loudly about nothing and muttering into their drink. They are unhappy about the company not achieving the goal everyone agreed on.%SPEECH_ON%Certainly we could chase this task we set ourselves across the world and back, just as we could spend our days chasing butterflies, but if it cannot be done let's put this misfortune behind us and move on to what we do best: fighting, drinking, and spending our hard-earned coin!%SPEECH_OFF%%highestexperience_brother% encourages his brothers-in-arms. These words placate the men somewhat and you are relieved not to have a revolt on your hands. | As you walk around the tents of the camp, %randombrother% approaches to complain.%SPEECH_ON%I seem to recall signing up with a band of merciless fighting men. Men who let nothing stand in their path. Now the %companyname% feels more like a squad of tired children than an unstoppable force.%SPEECH_OFF%He pauses, bites his lips.%SPEECH_ON%Captain, sir, I mean.%SPEECH_OFF%You nod and continue on your way. Clearly, the man is upset about the company's inability to fulfill the goal you announced to the men not long ago. | Despite your best efforts, you failed in fulfilling your latest ambition on the company's path to greatness. Worse, the men are all keenly aware of it, and seem more put out by this failure than you are. Feet are dragging, heads hanging, and griping and discontent louder than usual.\n\nStill, the sun rises just the same, and to worry over one's failures is to waste time better spent on new opportunities. You know that the men of the %companyname% will ride out this setback and march on to greater glories. Or die in the attempt. | After much striving and effort, you are finally forced to give up on the ambition you chose for the %companyname% to pursue. A mercenary company must face many setbacks on the road to greatness, but this latest failure to follow through has been especially bitter for the men. It would be wise to secure a lucrative contract or provide some other distraction, perhaps the threat of imminent death, to distract them from their unhappiness. | After you tell the men that the company isn't going to be able to do what you so proudly announced it would accomplish, the men grow standoffish and moody. Like sulky children they turn away when you come near and whisper their complaints whenever your back is turned.%SPEECH_ON%How are we ever going to be famous if we don't finish what we started? I want to be known wherever we go, and have our drinks poured before we walk in the door.%SPEECH_OFF%}\""
  },
  {
    "ID": 293416878,
    "key": "During camp...",
    "original": "During camp...",
    "translation": "露营时……",
    "stage": 5,
    "context": "this.m.Title = 'During camp...'"
  },
  {
    "ID": 293416879,
    "key": "Lost confidence in your leadership",
    "original": "Lost confidence in your leadership",
    "translation": "怀疑你的领导能力",
    "stage": 1,
    "context": "bro.worsenMood(this.Const.MoodChange.AmbitionFailed, 'Lost confidence in your leadership')"
  }
]
