name: 从 ParaTranz 同步翻译进度

on:
  schedule:
  # 每天0点(UTC时间)执行 1 次
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      forceUpdate:
         description: '强制更新?'
         required: true
         default: 'false'
         type: choice
         options:
          - 'true'
          - 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Build Tools And Sync from ParaTranz
      env:
        PARATRANZ_API_TOKEN: ${{ secrets.PARATRANZ_API_TOKEN }}
      run: |
        make sync-from-paratranz
        if [ "${{ inputs.forceUpdate }}" == "true" ]; then
          echo "force updating!!!"
          ./bin/sync-from-paratranz --token ${PARATRANZ_API_TOKEN} --project 7032 --force
        else
          ./bin/sync-from-paratranz --token ${PARATRANZ_API_TOKEN} --project 7032   
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ github.token }}
        commit-message: 'Auto Sync From ParaTranz'
        title: 'Auto Sync From ParaTranz'
        body: 'This is an automated PR'
        branch: 'auto-sync'
        base: 'main'
        assignees: 'shabbywu'
